import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  LocalizationService({String initialLanguage = 'en'})
      : _languageCode = initialLanguage {
    unawaited(_loadSavedLanguage());
  }

  static const String _prefsKey = 'customer_language_code';

  // NEW (Aug 12 2026 — Nizam's "personal touch" request): shared by both
  // the Customer and Hero home headers (see dashboard_screen.dart /
  // hero_home_screen.dart) so the same hour-of-day → greeting-key
  // mapping is defined exactly once. Plain wall-clock hour on the
  // device — no timezone lookup needed since this app only ever serves
  // Tamil Nadu (see the multi-city work elsewhere in this codebase).
  static String greetingKeyForNow() {
    final hour = DateTime.now().hour;
    if (hour >= 5 && hour < 12) return 'greeting_morning';
    if (hour >= 12 && hour < 17) return 'greeting_afternoon';
    if (hour >= 17 && hour < 21) return 'greeting_evening';
    return 'greeting_night';
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'my allin1',
      'greeting': 'Hello',
      'what_need_today': 'What do you need today?',
      'bike_taxi_title': 'Bike Taxi',
      'bike_taxi_subtitle': 'Fast rides in Erode',
      'food_delivery_title': 'Food Delivery',
      'food_delivery_subtitle': '16th Road specials',
      'grocery_title': 'Grocery',
      'grocery_subtitle': 'Fresh and fast',
      'tech_store_title': 'Tech Store',
      'tech_store_subtitle': 'NJ TECH gadgets',
      'custom_order_title': 'Custom Order',
      'custom_order_subtitle': 'Ask for special service',
      'broadband_title': 'Broadband / WiFi',
      'broadband_subtitle': 'Manage your internet service',
      'mobile_puncture_title': 'Mobile Puncture',
      'mobile_puncture_subtitle': 'Fast puncture repair',
      'pharmacy_title': 'Pharmacy',
      'pharmacy_subtitle': 'Medicines delivered',
      'book_puncture': 'Book for Puncture?',
      'call_now': 'Call Now',
      'later': 'Later',
      'service_coming_soon': 'Launching soon!',
      'language_label': 'Language',
      'home_label': 'Home',
      'chat_label': 'Live Rates',
      'rides_label': 'Play Zone',
      'account_label': 'Account',
      'my_rides_label': 'My Rides',
      'live_rates_label': 'Live Rates',
      'play_zone_label': 'Play Zone',
      'live_label': 'Live',
      'erode_label': 'Erode, Tamil Nadu',
      'live_rates_title': 'Live Rates',
      'live_rates_subtitle':
          'Gold, silver and fuel prices in one quick glance for Erode.',
      'today_price_label': "Today's Price",
      'play_zone_title': 'Play Zone',
      'play_zone_subtitle':
          'Solve the 3x3 NJ TECH puzzle and beat your best time.',
      'sliding_puzzle_title': 'Sliding Puzzle Game',
      'moves_label': 'Moves',
      'time_label': 'Time',
      'reset_label': 'Reset',
      'play_again_label': 'Play Again',
      'puzzle_instruction':
          'Align the NJ TECH and Erode pattern pieces perfectly.',
      'solved_title': 'You solved it!',
      'solved_message_intro': 'Brilliant moves!',
      'bike_label': 'Bike',
      'auto_label': 'Auto',
      'cab_label': 'Cab',
      'parcel_label': 'Parcel',
      'mini_truck_label': 'Mini Truck',
      'lorry_label': 'Lorry',
      'emergency_manpower_label': 'SOS',
      'where_to_go_hint': 'Where do you want to go?',
      'choose_vehicle_label': 'Choose Vehicle',
      'distance_label': 'Distance',
      'eta_label': 'ETA',
      'choose_destination_title': 'Choose destination',
      'update_pickup_title': 'Update pickup',
      'drag_map_hint':
          'Drag the map or type 3 letters to find a place in Erode.',
      'pickup_location_label': 'Pickup location',
      'drop_destination_label': 'Drop destination',
      'drop_pin_destination_title': 'Drop pin for destination',
      'drop_pin_pickup_title': 'Drop pin for pickup',
      'finding_street_label': 'Finding the exact street address...',
      'move_map_to_select_label': 'Move the map to select',
      'use_as_destination_label': 'Use as Destination',
      'use_as_pickup_label': 'Use as Pickup',
      'pay_via_soundbox': 'Pay your bill via Paytm box',
      'scan_soundbox_qr': 'Scan the physical soundbox QR and confirm once the amount is paid.',
      'awaiting_hero_payment': 'Waiting for Hero Confirmation...',
      'scan_and_wait_hero': 'Please scan the Paytm Soundbox and wait while the Hero confirms your bill.',
      'open_upi_scan_soundbox': 'Open Paytm through the UPI chooser, scan the Hero Paytm Soundbox, and complete the exact bill amount.',
      // ── Home screen "mega card" titles/subtitles (Nizam's whole-app
      // language retrofit, phase 1: dashboard_screen.dart) ──
      'hero_booking_mega_title': 'Hero Booking',
      'hero_booking_mega_subtitle': 'Hire a Hero for any tasks & deliveries',
      'taxi_mega_title': 'Taxi & Transportation',
      'taxi_mega_subtitle': 'Bike, Auto, Cab, Parcel & Rent',
      'food_mega_subtitle': 'Order from ANY shop in Erode!',
      'grocery_mega_title': 'Grocery Order',
      'grocery_mega_subtitle': 'Type your list or snap a photo',
      'electronics_mega_title': 'Electronic Services',
      'electronics_mega_subtitle': 'Mobile, Laptop, PC, CCTV, TV & AC',
      'mobiles_mega_title': 'Mobiles',
      'mobiles_mega_subtitle': 'New & used phones, repair, best offers',
      'carservice_mega_title': 'Car Service & Wash',
      'carservice_mega_subtitle': 'Water Wash, Repairs & Old Spares',
      'construction_mega_title': 'Constructions & Building',
      'construction_mega_subtitle': 'Usha Constructions, Contracts & Plans',
      'electrician_mega_title': 'Electrician',
      'electrician_mega_subtitle': 'Wiring, switchboard & appliance faults',
      'puncture_mega_title': 'Puncture / Tyre',
      'puncture_mega_subtitle': 'Flat tyre or air top-up, tracked live',
      'internet_mega_title': 'Internet & Broadband',
      'internet_mega_subtitle': 'Fast recharge plans & broadband deals',
      'printing_mega_title': 'Designing & Printing',
      'printing_mega_subtitle': 'Visiting Cards, Flex, Bill Books & Notices',
      'eseva_mega_title': 'E-Seva Online Services',
      'eseva_mega_subtitle': 'PAN, Aadhaar, Passport, Voter ID & more',
      'hero_guide_title': 'How to register (3 steps)',
      'hero_guide_hint': 'Tap to see what you need',
      'hero_guide_s1_title': 'Fill your details',
      'hero_guide_s1_body': 'Name, phone, date of birth, address and your city. Use "Use my current location", or pick your city manually.',
      'hero_guide_s2_title': 'Add your documents',
      'hero_guide_s2_body': 'Driving License, Aadhaar and PAN — number plus a clear photo of each. Then take one live selfie in good lighting.',
      'hero_guide_s3_title': 'Submit and wait for approval',
      'hero_guide_s3_body': 'Pick your vehicle category, accept the SOS agreement, then Submit. Admin verifies and calls you — usually within 2-4 hours.',
      'hero_guide_tip': 'Tip: keep all documents ready before you start. Trouble uploading? Use the WhatsApp button below.',
      'otherservices_mega_title': 'Other Services',
      'otherservices_mega_subtitle': 'Broadband, Mobile Puncture & More',
      'other_internet_label': 'Internet',
      'other_puncture_label': 'Puncture',
      'other_cleaning_label': 'Cleaning',
      'other_electrician_label': 'Electrician',
      'greeting_hi': 'Hi',
      // NEW (Aug 12 2026 — Nizam's "personal touch" request): time-of-day
      // greeting shown on both the Customer and Hero home headers (see
      // dashboard_screen.dart / hero_home_screen.dart), replacing the
      // always-on generic 'greeting_hi'. Picked by hour-of-day — see
      // greeting_utils.dart's timeGreetingKey().
      'greeting_morning': 'Good morning',
      'greeting_afternoon': 'Good afternoon',
      'greeting_evening': 'Good evening',
      'greeting_night': 'Good night',
      // ── Food Hub screen ──
      'food_hub_prompt': 'What would you like to order?',
      'food_hub_custom_subtitle': 'Order from any shop in Erode',
      'food_hub_shops_heading': 'Order from your favourite shops',
      'food_hub_shops_subheading': 'Order & pay on their site — our hero picks it up & delivers it to you.',
      // ── Settings screen (Nizam's i18n phase 1: settings_screen.dart) ──
      'settings_title': 'Settings',
      'notifications_section': 'Notifications',
      'push_notifications_title': 'Push Notifications',
      'push_notifications_subtitle': 'Receive push notifications',
      'ride_alerts_title': 'Ride Alerts',
      'ride_alerts_subtitle': 'Get updates about your rides',
      'promotional_alerts_title': 'Promotional Alerts',
      'promotional_alerts_subtitle': 'Offers and deals',
      'preferences_section': 'Preferences',
      'location_services_title': 'Location Services',
      'location_services_subtitle': 'Allow app to access location',
      'biometric_login_title': 'Biometric Login',
      'biometric_login_subtitle': 'Use fingerprint for quick login',
      'dark_mode_title': 'Dark Mode',
      'dark_mode_subtitle': 'Dark theme is currently active',
      'theme_title': 'Theme',
      'theme_subtitle': 'Pick your favourite look',
      'map_provider_section': 'Map Provider',
      'language_region_section': 'Language & Region',
      'privacy_security_section': 'Privacy & Security',
      'about_section': 'About',
      'language_picker_title': 'Language / Mozhi',
      'language_picker_subtitle': 'Pick how you want app text to look',
      'map_provider_info_title': 'Map Provider (Auto-Managed)',
      'map_provider_fallback': 'Using OpenStreetMap (Ola Maps unavailable)',
      'map_provider_primary': 'Using Ola Maps (Primary)',
      'privacy_policy_title': 'Privacy Policy',
      'privacy_policy_subtitle': 'View our privacy policy',
      'terms_title': 'Terms of Service',
      'terms_subtitle': 'View terms and conditions',
      'delete_account_title': 'Delete Account',
      'delete_account_subtitle': 'Permanently delete your account',
      'rate_app_title': 'Rate App',
      'rate_app_subtitle': 'Rate us on Play Store',
      'share_app_title': 'Share App',
      'share_app_subtitle': 'Invite friends to join',
      'help_support_title': 'Help & Support',
      'help_support_subtitle': 'Get help with issues',
      'share_link_copied_snack': 'Link copied! Share it with your friends.',
      'could_not_open_link_snack': 'Could not open link',
      'app_version_name': 'Allin1 Super App',
      'app_version_number': 'Version 1.0.0 (Build 1)',
      'app_made_with_love': 'Made with ❤️ in Erode',
      'delete_account_dialog_title': 'Delete Account?',
      'delete_account_dialog_body': 'This action cannot be undone. All your data including ride history, saved addresses, and payment methods will be permanently deleted.',
      'cancel_label': 'Cancel',
      'delete_label': 'Delete',
      'delete_account_requested_snack': 'Account deletion requested. Contact support for assistance.',
      'select_currency_title': 'Select Currency',
      'currency_inr_name': 'Indian Rupee',
      'currency_usd_name': 'US Dollar',
      'currency_eur_name': 'Euro',
      'exit_app_title': 'Leave the app?',
      'exit_app_body': 'Close Allin1?',
      'press_home_to_minimize': "Press your device's Home button to minimize",
      'no_label': 'No',
      'yes_label': 'Yes',
      'nav_home_label': 'Home',
      'nav_rewards_label': 'Rewards',
      'nav_playzone_label': 'Play Zone',
      'nav_guru_label': 'Chitti AI',
      'nav_safety_label': 'Safety',
      'select_city_title': 'Select City',
      'use_current_location_label': 'Use my current location',
      'featured_shop_badge': '★ Featured Shop',
      'shop_open_label': 'Open',
      'erode_fresh_name': 'Erode Fresh',
      'erode_fresh_subtitle': '★★  · Fresh Groceries',
      'promo_free_ride_title': 'Your first ride is FREE!',
      'promo_free_ride_subtitle': 'Book a Bike Taxi anywhere in Erode',
      'promo_book_label': 'Book →',
      'promo_guru_title': 'Get your Chitti AI subscription for 1yr free',
      'promo_guru_badge': 'CHITTI',
      'promo_guru_subtitle': 'Visit NJ TECH to unlock the 1-year free Chitti AI offer.',
      'drawer_my_profile': 'My Profile',
      'drawer_activity': 'Activity',
      'drawer_settings': 'Settings',
      'drawer_help_whatsapp': 'Help & WhatsApp Support',
      'drawer_check_update': 'Check for update',
      'drawer_download_app_title': 'Download the Turbo App!',
      'drawer_download_app_subtitle': 'Get the app & run 10x faster!',
      'drawer_sign_out': 'Sign Out / Logout',
      'app_version_footer': 'Allin1 Super App v1.0.0',
      'checking_updates_msg': 'Checking for updates...',
      'app_updating_msg': 'Please wait, app is updating...',
      'up_to_date_title': 'Up to Date',
      'up_to_date_body': 'App is up to date!\nBackground updates are active via Shorebird OTA.',
      'got_it_label': 'Got it',
      'already_latest_version_snack': "You're already on the latest version",
      'welcome_new_version_title': "You're all set!",
      'welcome_new_version_body': 'Welcome to the newest version of Allin1 — enjoy the latest fixes and features.',
      'updating_app_msg': 'Updating the app...',
      'download_failed_title': "Couldn't start download",
      'download_failed_body': 'Your browser blocked the direct download. Copy this link and open it in Chrome instead:',
      'copy_link_label': 'Copy Link',
      'close_label': 'Close',
      'link_copied_snack': 'Link copied',
      'apk_sheet_title': '📲 Download NJ TECH Apps',
      'download_customer_app_label': '🛒  Download Customer App',
      'download_hero_app_label': '🏍️  Download Hero App',
      'dismiss_label': 'Dismiss',
      'reload_tooltip': 'Reload',
      'opening_erode_fiber_msg': 'Opening Erode Fiber...',
      'erode_fiber_open_title': 'Erode Fiber is open!',
      'erode_fiber_open_subtitle': 'The site loaded in-app above.',
      'back_to_dashboard_label': '← Back to Dashboard',
      'could_not_open_inapp_title': 'Could not open in-app',
      'check_internet_retry_subtitle': 'Check internet and try again.',
      'try_again_label': 'Try Again',
      'daily_scratch_badge': '🎰 SCRATCH & WIN',
      'scratch_reveal_hint': 'Scratch to reveal your gift!',
      'scratch_reward_title': 'You won a Paytm Soundbox!',
      'scratch_reward_subtitle': 'Tap below to claim your reward',
      'scratch_revealed_label': '🎊 Revealed!',
      'scratch_keep_going_label': 'Keep scratching...',
      'call_to_claim_label': '📞 Call to Claim',
      'update_badge_label': 'UPDATE',
      'category_taxi_slide': '🚕 Taxi & Transport',
      'category_food_slide': '🍔 Food Delivery',
      'category_grocery_slide': '🛒 Groceries',
      'category_services_slide': '🔧 Services',
      'downloading_update_snack': 'Downloading update...',
      'promo_firstride_title': 'First Ride FREE 🛵',
      'promo_firstride_subtitle': 'New user? Your first taxi ride is on us!',
      'promo_book_now_label': 'Book Now',
      'promo_new_users_label': 'New Users',
      'promo_claimed_label': 'Claimed ✓',
      'tour_welcome_title': 'Welcome to Allin1! 👋',
      'tour_welcome_desc': 'Everything Erode needs in one app — bike taxi, food delivery, grocery, tech store, and more. Quick tour of the basics?',
      'tour_home_desc': 'Book a taxi, order food/grocery, or ask for any custom service — all from here.',
      'tour_rewards_desc': 'Answer quick quizzes to unlock real rewards like a free Paytm box or a Chitti AI subscription.',
      'tour_playzone_desc': 'Play quick games like 2048 and Whack-a-Mole while you wait for your ride or order.',
      'tour_guru_desc': 'Your AI assistant — ask it anything about booking, tracking, or the app in general.',
      'tour_safety_desc': 'One-tap SOS emergency help, verified for real safety when you need it most.',
      'eseva_xerox': 'Xerox & Colour Printout',
      'eseva_voter_id': 'Voter ID Card',
      'eseva_pan': 'PAN Card',
      'eseva_aadhaar': 'Aadhaar Card Update',
      'eseva_rental': 'Rental Agreement & Job Typing',
      'eseva_employment': 'Employment Registration',
      'eseva_ration': 'Ration Card',
      'eseva_birth_death': 'Birth & Death Certificate',
      'eseva_fssai_msme': 'FSSAI / MSME / UDYAM',
      'eseva_certificate': 'Income, Nativity & Community Certificate',
      'eseva_ayushman': 'Ayushman Card (5L Insurance)',
      'eseva_eshram': 'E-Shram Card',
      'eseva_laptop': 'Laptop & Computer Sales/Service',
      'eseva_photo_print': 'Photo Print',
      'eseva_pvc': 'PVC Plastic Card Print',
    },
    'ta': {
      'app_title': 'my allin1',
      'greeting': 'வணக்கம்',
      'what_need_today': 'இன்று என்ன வேண்டும்?',
      'bike_taxi_title': 'பைக் டாக்ஸி',
      'bike_taxi_subtitle': 'ஈரோட்டில் வேகமான பயணம்',
      'food_delivery_title': 'உணவு டெலிவரி',
      'food_delivery_subtitle': '16வது ரோடு சிறப்புகள்',
      'grocery_title': 'மளிகை',
      'grocery_subtitle': 'புதியதும் வேகமும்',
      'tech_store_title': 'டெக் ஸ்டோர்',
      'tech_store_subtitle': 'NJ TECH சாதனங்கள்',
      'custom_order_title': 'கஸ்டம் ஆர்டர்',
      'custom_order_subtitle': 'சிறப்பு சேவையை கேளுங்கள்',
      'broadband_title': 'இணைய சேவை',
      'broadband_subtitle': 'உங்கள் இணைய சேவையை நிர்வகிக்கவும்',
      'mobile_puncture_title': 'மொபைல் பஞ்சர்',
      'mobile_puncture_subtitle': 'விரைவு பஞ்சர் பழுது பார்க்க',
      'pharmacy_title': 'மருந்தகம்',
      'pharmacy_subtitle': 'மருந்துகள் டெலிவரி',
      'book_puncture': 'பஞ்சருக்கு புக் செய்யவா?',
      'call_now': 'இப்போதே அழைக்கவும்',
      'later': 'பிறகு',
      'service_coming_soon': 'விரைவில் வருகிறது!',
      'language_label': 'மொழி',
      'home_label': 'முகப்பு',
      'chat_label': 'நேரலை விலைகள்',
      'rides_label': 'ப்ளே சோன்',
      'account_label': 'கணக்கு',
      'my_rides_label': 'என் பயணங்கள்',
      'live_rates_label': 'நேரலை விலைகள்',
      'play_zone_label': 'ப்ளே சோன்',
      'live_label': 'நேரலை',
      'erode_label': 'ஈரோடு, தமிழ்நாடு',
      'live_rates_title': 'நேரலை விலைகள்',
      'live_rates_subtitle':
          'ஈரோட்டிற்கான தங்கம், வெள்ளி, எரிபொருள் விலைகள் ஒரே பார்வையில்.',
      'today_price_label': 'இன்றைய விலை',
      'play_zone_title': 'ப்ளே சோன்',
      'play_zone_subtitle':
          'NJ TECH 3x3 புதிரை தீர்த்து உங்கள் சிறந்த நேரத்தை வெல்லுங்கள்.',
      'sliding_puzzle_title': 'சறுக்கும் புதிர் விளையாட்டு',
      'moves_label': 'நகர்வுகள்',
      'time_label': 'நேரம்',
      'reset_label': 'மீட்டமை',
      'play_again_label': 'மீண்டும் விளையாடு',
      'puzzle_instruction':
          'NJ TECH மற்றும் ஈரோடு வடிவங்களை சரியாக ஒழுங்குபடுத்து.',
      'solved_title': 'நீங்கள் தீர்த்துவிட்டீர்கள்!',
      'solved_message_intro': 'சிறப்பான நகர்வுகள்!',
      'bike_label': 'பைக்',
      'auto_label': 'ஆட்டோ',
      'cab_label': 'கார்',
      'parcel_label': 'பார்சல்',
      'where_to_go_hint': 'எங்கே செல்ல வேண்டும்?',
      'choose_vehicle_label': 'வாகனத்தை தேர்வு செய்',
      'distance_label': 'தூரம்',
      'eta_label': 'நேரம்',
      'choose_destination_title': 'இறங்கும் இடத்தை தேர்வு செய்',
      'update_pickup_title': 'பிக்கப் இடத்தை மாற்று',
      'drag_map_hint':
          'ஈரோட்டில் இடம் காண மேப்பை இழுக்கவும் அல்லது 3 எழுத்துகள் தட்டச்சு செய்யவும்.',
      'pickup_location_label': 'பிக்கப் இடம்',
      'drop_destination_label': 'இறங்கும் இடம்',
      'drop_pin_destination_title': 'இறங்கும் இடத்திற்கு பின் இடு',
      'drop_pin_pickup_title': 'பிக்கப் இடத்திற்கு பின் இடு',
      'finding_street_label': 'சரியான தெரு முகவரியை கண்டுபிடிக்கிறது...',
      'move_map_to_select_label': 'தேர்வு செய்ய மேப்பை நகர்த்து',
      'use_as_destination_label': 'இறங்கும் இடமாக பயன்படுத்து',
      'use_as_pickup_label': 'பிக்கப் இடமாக பயன்படுத்து',
      'pay_via_soundbox': 'Paytm சவுண்ட்பாக்ஸ் மூலம் பில் செலுத்தவும்',
      'scan_soundbox_qr': 'சவுண்ட்பாக்ஸ் QR ஐ ஸ்கேன் செய்து, பணம் செலுத்தியதும் உறுதிசெய்யவும்.',
      'awaiting_hero_payment': 'ஹீரோ உறுதிப்படுத்தலுக்காக காத்திருக்கிறது...',
      'scan_and_wait_hero': 'Paytm சவுண்ட்பாக்ஸை ஸ்கேன் செய்து, ஹீரோ உங்கள் பில்லை உறுதிப்படுத்தும் வரை காத்திருக்கவும்.',
      'open_upi_scan_soundbox': 'UPI தேர்வு மூலம் Paytm ஐ திறந்து, ஹீரோவின் Paytm சவுண்ட்பாக்ஸை ஸ்கேன் செய்து, சரியான பில் தொகையை செலுத்தவும்.',
      'hero_booking_mega_title': 'ஹீரோ புக்கிங்',
      'hero_booking_mega_subtitle': 'எந்த வேலைக்கும் டெலிவரிக்கும் ஹீரோவை அமர்த்துங்கள்',
      'taxi_mega_title': 'டாக்ஸி & போக்குவரத்து',
      'taxi_mega_subtitle': 'பைக், ஆட்டோ, கார், பார்சல் & வாடகை',
      'food_mega_subtitle': 'ஈரோட்டில் எந்த கடையிலிருந்தும் ஆர்டர் செய்யுங்கள்!',
      'grocery_mega_title': 'மளிகை ஆர்டர்',
      'grocery_mega_subtitle': 'உங்கள் லிஸ்ட்டை டைப் செய்யுங்கள் அல்லது புகைப்படம் எடுங்கள்',
      'electronics_mega_title': 'எலக்ட்ரானிக் சேவைகள்',
      'electronics_mega_subtitle': 'மொபைல், லேப்டாப், பிசி, சிசிடிவி, டிவி & ஏசி',
      'mobiles_mega_title': 'மொபைல்கள்',
      'mobiles_mega_subtitle': 'புதிய & பழைய போன், சர்வீஸ், சிறந்த ஆஃபர்',
      'carservice_mega_title': 'கார் சர்வீஸ் & வாஷ்',
      'carservice_mega_subtitle': 'வாட்டர் வாஷ், ரிப்பேர் & பழைய பாகங்கள்',
      'construction_mega_title': 'கட்டுமானம் & பில்டிங்',
      'construction_mega_subtitle': 'உஷா கன்ஸ்ட்ரக்சன்ஸ், ஒப்பந்தங்கள் & திட்டங்கள்',
      'electrician_mega_title': 'எலெக்ட்ரீஷியன்',
      'electrician_mega_subtitle': 'வயரிங், சுவிட்ச்போர்டு & அப்ளையன்ஸ் பழுது',
      'puncture_mega_title': 'பஞ்சர் / டயர்',
      'puncture_mega_subtitle': 'ஃபிளாட் டயர் அல்லது ஏர் டாப்-அப், லைவ் ட்ராக்கிங்',
      'internet_mega_title': 'இன்டர்நெட் & ப்ராட்பேண்ட்',
      'internet_mega_subtitle': 'வேகமான ரீசார்ஜ் & ப்ராட்பேண்ட் ஆஃபர்கள்',
      'printing_mega_title': 'டிசைனிங் & பிரிண்டிங்',
      'printing_mega_subtitle': 'விசிட்டிங் கார்டு, ஃப்ளெக்ஸ், பில் புக்ஸ் & நோட்டீஸ்',
      'eseva_mega_title': 'இ-சேவா ஆன்லைன் சேவைகள்',
      'eseva_mega_subtitle': 'பான், ஆதார், பாஸ்போர்ட், வாக்காளர் அட்டை & மேலும்',
      'hero_guide_title': 'எப்படி பதிவு செய்வது (3 படிகள்)',
      'hero_guide_hint': 'என்ன தேவை என்று பார்க்க தட்டவும்',
      'hero_guide_s1_title': 'உங்கள் விவரங்களை நிரப்புங்கள்',
      'hero_guide_s1_body': 'பெயர், தொலைபேசி, பிறந்த தேதி, முகவரி மற்றும் உங்கள் நகரம். "எனது தற்போதைய இருப்பிடம்" பயன்படுத்தவும் அல்லது நகரத்தை நீங்களே தேர்ந்தெடுக்கவும்.',
      'hero_guide_s2_title': 'உங்கள் ஆவணங்களைச் சேர்க்கவும்',
      'hero_guide_s2_body': 'ஓட்டுநர் உரிமம், ஆதார் மற்றும் பான் — எண் மற்றும் ஒவ்வொன்றின் தெளிவான புகைப்படம். பிறகு நல்ல வெளிச்சத்தில் ஒரு நேரடி செல்ஃபி எடுக்கவும்.',
      'hero_guide_s3_title': 'சமர்ப்பித்து ஒப்புதலுக்குக் காத்திருங்கள்',
      'hero_guide_s3_body': 'உங்கள் வாகன வகையைத் தேர்ந்தெடுத்து, SOS ஒப்பந்தத்தை ஏற்று, சமர்ப்பிக்கவும். நிர்வாகம் சரிபார்த்து உங்களை அழைப்பார் — பொதுவாக 2-4 மணி நேரத்தில்.',
      'hero_guide_tip': 'குறிப்பு: தொடங்குவதற்கு முன் அனைத்து ஆவணங்களையும் தயாராக வைத்திருங்கள். பதிவேற்றுவதில் சிக்கலா? கீழே உள்ள WhatsApp பொத்தானைப் பயன்படுத்தவும்.',
      'otherservices_mega_title': 'மற்ற சேவைகள்',
      'otherservices_mega_subtitle': 'ப்ராட்பேண்ட், மொபைல் பஞ்சர் & மேலும்',
      'other_internet_label': 'இணையம்',
      'other_puncture_label': 'பஞ்சர்',
      'other_cleaning_label': 'சுத்தம்',
      'other_electrician_label': 'எலக்ட்ரீஷியன்',
      'greeting_hi': 'ஹாய்',
      'greeting_morning': 'காலை வணக்கம்',
      'greeting_afternoon': 'மதிய வணக்கம்',
      'greeting_evening': 'மாலை வணக்கம்',
      'greeting_night': 'இரவு வணக்கம்',
      'food_hub_prompt': 'என்ன ஆர்டர் செய்ய விரும்புகிறீர்கள்?',
      'food_hub_custom_subtitle': 'ஈரோட்டில் எந்த கடையிலிருந்தும் ஆர்டர் செய்யுங்கள்',
      'food_hub_shops_heading': 'உங்களுக்கு பிடித்த கடைகளிலிருந்து ஆர்டர் செய்யுங்கள்',
      'food_hub_shops_subheading': 'அவர்களின் தளத்தில் ஆர்டர் செய்து பணம் செலுத்துங்கள் — எங்கள் ஹீரோ அதை எடுத்து உங்களிடம் கொண்டு வருவார்.',
      'settings_title': 'அமைப்புகள்',
      'notifications_section': 'அறிவிப்புகள்',
      'push_notifications_title': 'புஷ் அறிவிப்புகள்',
      'push_notifications_subtitle': 'புஷ் அறிவிப்புகளைப் பெறவும்',
      'ride_alerts_title': 'பயண அறிவிப்புகள்',
      'ride_alerts_subtitle': 'உங்கள் பயணங்கள் பற்றிய அறிவிப்புகள்',
      'promotional_alerts_title': 'விளம்பர அறிவிப்புகள்',
      'promotional_alerts_subtitle': 'சலுகைகள் & ஆஃபர்கள்',
      'preferences_section': 'விருப்பங்கள்',
      'location_services_title': 'இருப்பிட சேவைகள்',
      'location_services_subtitle': 'இருப்பிடத்தை அணுக அனுமதிக்கவும்',
      'biometric_login_title': 'பயோமெட்ரிக் லாகின்',
      'biometric_login_subtitle': 'விரைவு லாகினுக்கு கைரேகையை பயன்படுத்தவும்',
      'dark_mode_title': 'டார்க் மோட்',
      'dark_mode_subtitle': 'டார்க் தீம் தற்போது இயக்கத்தில் உள்ளது',
      'theme_title': 'தீம்',
      'theme_subtitle': 'உங்களுக்கு பிடித்த தோற்றத்தை தேர்வு செய்யவும்',
      'map_provider_section': 'மேப் வழங்குநர்',
      'language_region_section': 'மொழி & பகுதி',
      'privacy_security_section': 'தனியுரிமை & பாதுகாப்பு',
      'about_section': 'பற்றி',
      'language_picker_title': 'மொழி / Mozhi',
      'language_picker_subtitle': 'ஆப் டெக்ஸ்ட் எப்படி இருக்க வேண்டும் என தேர்வு செய்யவும்',
      'map_provider_info_title': 'மேப் வழங்குநர் (தானியங்கி)',
      'map_provider_fallback': 'OpenStreetMap பயன்படுத்தப்படுகிறது (Ola Maps கிடைக்கவில்லை)',
      'map_provider_primary': 'Ola Maps பயன்படுத்தப்படுகிறது (முதன்மை)',
      'privacy_policy_title': 'தனியுரிமைக் கொள்கை',
      'privacy_policy_subtitle': 'எங்கள் தனியுரிமைக் கொள்கையைப் பார்க்கவும்',
      'terms_title': 'சேவை விதிமுறைகள்',
      'terms_subtitle': 'விதிமுறைகள் & நிபந்தனைகளைப் பார்க்கவும்',
      'delete_account_title': 'கணக்கை நீக்கு',
      'delete_account_subtitle': 'உங்கள் கணக்கை நிரந்தரமாக நீக்கவும்',
      'rate_app_title': 'ஆப்பை மதிப்பிடுங்கள்',
      'rate_app_subtitle': 'Play Store-ல் எங்களை மதிப்பிடுங்கள்',
      'share_app_title': 'ஆப்பைப் பகிரவும்',
      'share_app_subtitle': 'நண்பர்களை இணைய அழைக்கவும்',
      'help_support_title': 'உதவி & ஆதரவு',
      'help_support_subtitle': 'சிக்கல்களுக்கு உதவி பெறவும்',
      'share_link_copied_snack': 'லிங்க் காபி செய்யப்பட்டது! உங்கள் நண்பர்களுடன் பகிரவும்.',
      'could_not_open_link_snack': 'லிங்க் திறக்க முடியவில்லை',
      'app_version_name': 'Allin1 சூப்பர் ஆப்',
      'app_version_number': 'பதிப்பு 1.0.0 (பில்ட் 1)',
      'app_made_with_love': 'ஈரோட்டில் ❤️ உடன் உருவாக்கப்பட்டது',
      'delete_account_dialog_title': 'கணக்கை நீக்கவா?',
      'delete_account_dialog_body': 'இந்த செயலை மீட்டெடுக்க முடியாது. உங்கள் பயண வரலாறு, சேமிக்கப்பட்ட முகவரிகள் மற்றும் கட்டண முறைகள் உட்பட அனைத்து தரவும் நிரந்தரமாக நீக்கப்படும்.',
      'cancel_label': 'ரத்து செய்',
      'delete_label': 'நீக்கு',
      'delete_account_requested_snack': 'கணக்கு நீக்கம் கோரப்பட்டது. உதவிக்கு ஆதரவைத் தொடர்பு கொள்ளவும்.',
      'select_currency_title': 'நாணயத்தைத் தேர்வு செய்யவும்',
      'currency_inr_name': 'இந்திய ரூபாய்',
      'currency_usd_name': 'அமெரிக்க டாலர்',
      'currency_eur_name': 'யூரோ',
      'exit_app_title': 'ஆப்ஸை விட்டு வெளியேறவா?',
      'exit_app_body': 'Allin1-ஐ மூடவா?',
      'press_home_to_minimize': 'மினிமைஸ் செய்ய உங்கள் டிவைஸின் ஹோம் பட்டனை அழுத்தவும்',
      'no_label': 'இல்லை',
      'yes_label': 'ஆம்',
      'nav_home_label': 'முகப்பு',
      'nav_rewards_label': 'ரிவார்டுகள்',
      'nav_playzone_label': 'பிளே சோன்',
      'nav_guru_label': 'சிட்டி AI',
      'nav_safety_label': 'பாதுகாப்பு',
      'select_city_title': 'நகரத்தை தேர்வு செய்யவும்',
      'use_current_location_label': 'எனது தற்போதைய இருப்பிடத்தை பயன்படுத்து',
      'featured_shop_badge': '★ சிறப்பு கடை',
      'shop_open_label': 'திறந்துள்ளது',
      'erode_fresh_name': 'ஈரோடு ஃபிரெஷ்',
      'erode_fresh_subtitle': '★★  · புதிய மளிகை பொருட்கள்',
      'promo_free_ride_title': 'உங்கள் முதல் ரைடு இலவசம்!',
      'promo_free_ride_subtitle': 'ஈரோட்டில் எங்கும் பைக் டாக்ஸி புக் செய்யுங்கள்',
      'promo_book_label': 'புக் செய் →',
      'promo_guru_title': '1 வருட சிட்டி AI சந்தா இலவசமாக பெறுங்கள்',
      'promo_guru_badge': 'சிட்டி',
      'promo_guru_subtitle': '1 வருட இலவச சிட்டி AI ஆஃபரை பெற NJ TECH-ஐ பார்வையிடவும்.',
      'drawer_my_profile': 'எனது சுயவிவரம்',
      'drawer_activity': 'செயல்பாடு',
      'drawer_settings': 'அமைப்புகள்',
      'drawer_help_whatsapp': 'உதவி & WhatsApp ஆதரவு',
      'drawer_check_update': 'புதுப்பிப்பை சரிபார்க்கவும்',
      'drawer_download_app_title': 'டர்போ ஆப்ஸை பதிவிறக்கவும்!',
      'drawer_download_app_subtitle': 'ஆப்ஸை பெற்று 10x வேகமாக இயக்கவும்!',
      'drawer_sign_out': 'வெளியேறு / லாக் அவுட்',
      'app_version_footer': 'Allin1 சூப்பர் ஆப் v1.0.0',
      'checking_updates_msg': 'புதுப்பிப்புகளை சரிபார்க்கிறது...',
      'app_updating_msg': 'காத்திருக்கவும், ஆப் புதுப்பிக்கப்படுகிறது...',
      'up_to_date_title': 'புதுப்பித்த நிலையில் உள்ளது',
      'up_to_date_body': 'ஆப் புதுப்பித்த நிலையில் உள்ளது!\nShorebird OTA மூலம் பேக்கிரவுண்ட் அப்டேட்கள் இயங்குகின்றன.',
      'got_it_label': 'சரி புரிந்தது',
      'already_latest_version_snack': 'நீங்கள் ஏற்கனவே சமீபத்திய பதிப்பில் உள்ளீர்கள்',
      'welcome_new_version_title': 'நீங்கள் தயார்!',
      'welcome_new_version_body': 'Allin1-ன் புதிய பதிப்பிற்கு வரவேற்கிறோம் — புதிய திருத்தங்களையும் அம்சங்களையும் அனுபவியுங்கள்.',
      'updating_app_msg': 'ஆப் புதுப்பிக்கப்படுகிறது...',
      'download_failed_title': 'பதிவிறக்கத்தை தொடங்க முடியவில்லை',
      'download_failed_body': 'உங்கள் பிரவுசர் நேரடி பதிவிறக்கத்தை தடுத்தது. இந்த லிங்கை காபி செய்து Chrome-ல் திறக்கவும்:',
      'copy_link_label': 'லிங்கை காபி செய்',
      'close_label': 'மூடு',
      'link_copied_snack': 'லிங்க் காபி செய்யப்பட்டது',
      'apk_sheet_title': '📲 NJ TECH ஆப்ஸை பதிவிறக்கவும்',
      'download_customer_app_label': '🛒  கஸ்டமர் ஆப்பை பதிவிறக்கவும்',
      'download_hero_app_label': '🏍️  ஹீரோ ஆப்பை பதிவிறக்கவும்',
      'dismiss_label': 'மூடு',
      'reload_tooltip': 'மீண்டும் ஏற்று',
      'opening_erode_fiber_msg': 'ஈரோடு ஃபைபரை திறக்கிறது...',
      'erode_fiber_open_title': 'ஈரோடு ஃபைபர் திறந்துவிட்டது!',
      'erode_fiber_open_subtitle': 'சைட் ஆப்பிற்குள்ளேயே ஏற்றப்பட்டது.',
      'back_to_dashboard_label': '← டாஷ்போர்டுக்கு திரும்பு',
      'could_not_open_inapp_title': 'ஆப்பிற்குள் திறக்க முடியவில்லை',
      'check_internet_retry_subtitle': 'இணையத்தை சரிபார்த்து மீண்டும் முயற்சிக்கவும்.',
      'try_again_label': 'மீண்டும் முயற்சி செய்',
      'daily_scratch_badge': '🎰 ஸ்கிராட்ச் & வெல்லுங்கள்',
      'scratch_reveal_hint': 'உங்கள் பரிசை பார்க்க ஸ்கிராட்ச் செய்யுங்கள்!',
      'scratch_reward_title': 'நீங்கள் ஒரு Paytm சவுண்ட்பாக்ஸ் வென்றுள்ளீர்கள்!',
      'scratch_reward_subtitle': 'உங்கள் பரிசை பெற கீழே தட்டவும்',
      'scratch_revealed_label': '🎊 வெளிப்படுத்தப்பட்டது!',
      'scratch_keep_going_label': 'தொடர்ந்து ஸ்கிராட்ச் செய்யுங்கள்...',
      'call_to_claim_label': '📞 பெற அழைக்கவும்',
      'update_badge_label': 'அப்டேட்',
      'category_taxi_slide': '🚕 டாக்ஸி & போக்குவரத்து',
      'category_food_slide': '🍔 உணவு டெலிவரி',
      'category_grocery_slide': '🛒 மளிகை பொருட்கள்',
      'category_services_slide': '🔧 சேவைகள்',
      'downloading_update_snack': 'புதுப்பிப்பு பதிவிறக்கப்படுகிறது...',
      'promo_firstride_title': 'முதல் ரைடு இலவசம் 🛵',
      'promo_firstride_subtitle': 'புதிய பயனரா? உங்கள் முதல் டாக்ஸி ரைடு எங்கள் சார்பில்!',
      'promo_book_now_label': 'இப்போது புக் செய்',
      'promo_new_users_label': 'புதிய பயனர்கள்',
      'promo_claimed_label': 'பெறப்பட்டது ✓',
      'tour_welcome_title': 'Allin1-க்கு வரவேற்கிறோம்! 👋',
      'tour_welcome_desc': 'ஈரோட்டுக்கு தேவையான அனைத்தும் ஒரே ஆப்பில் — பைக் டாக்ஸி, உணவு டெலிவரி, மளிகை, டெக் ஸ்டோர் மற்றும் பல. அடிப்படைகளின் விரைவு சுற்றுலா?',
      'tour_home_desc': 'டாக்ஸி புக் செய், உணவு/மளிகை ஆர்டர் செய், அல்லது சிறப்பு சேவை கேளுங்கள் — எல்லாம் இங்கிருந்தே.',
      'tour_rewards_desc': 'இலவச Paytm பாக்ஸ் அல்லது சிட்டி AI சந்தா போன்ற உண்மையான ரிவார்டுகளை திறக்க விரைவு வினாடி வினாக்களுக்கு பதிலளிக்கவும்.',
      'tour_playzone_desc': 'உங்கள் ரைடு அல்லது ஆர்டருக்காக காத்திருக்கும்போது 2048, Whack-a-Mole போன்ற விரைவு விளையாட்டுகளை விளையாடுங்கள்.',
      'tour_guru_desc': 'உங்கள் AI உதவியாளர் — புக்கிங், டிராக்கிங் அல்லது ஆப் பற்றி எதுவும் கேளுங்கள்.',
      'tour_safety_desc': 'உங்களுக்கு தேவைப்படும் போது உண்மையான பாதுகாப்புக்கான ஒரு-தட்டு SOS அவசர உதவி.',
      'eseva_xerox': 'ஜெராக்ஸ் & கலர் பிரிண்ட் அவுட்',
      'eseva_voter_id': 'வாக்காளர் அட்டை',
      'eseva_pan': 'பான் கார்டு',
      'eseva_aadhaar': 'ஆதார் அட்டை சேவைகள்',
      'eseva_rental': 'வாடகை ஒப்பந்தம் & ஜாப் டைப்பிங்',
      'eseva_employment': 'வேலைவாய்ப்பு பதிவு',
      'eseva_ration': 'ரேஷன் அட்டை',
      'eseva_birth_death': 'பிறப்பு / இறப்பு சான்றிதழ்',
      'eseva_fssai_msme': 'FSSAI / MSME சான்றிதழ்',
      'eseva_certificate': 'வருமான, இருப்பிட & சாதி சான்றிதழ்',
      'eseva_ayushman': 'ஆயுஷ்மான் கார்டு',
      'eseva_eshram': 'E-Shram கார்டு',
      'eseva_laptop': 'லேப்டாப், கம்ப்யூட்டர் சேல்ஸ் & சர்வீஸ்',
      'eseva_photo_print': 'போட்டோ பிரிண்ட்',
      'eseva_pvc': 'PVC பிளாஸ்டிக் கார்டு பிரிண்ட்',
    },
    'tg': {
      'app_title': 'my allin1',
      'greeting': 'Vanakkam',
      'what_need_today': 'Innaiku enna venum?',
      'bike_taxi_title': 'Bike Taxi',
      'bike_taxi_subtitle': 'Erode la fast ride',
      'food_delivery_title': 'Food Delivery',
      'food_delivery_subtitle': '16th road special sapadu',
      'grocery_title': 'Grocery',
      'grocery_subtitle': 'Fresh ahum fast ahum',
      'tech_store_title': 'Tech Store',
      'tech_store_subtitle': 'NJ TECH gadgets',
      'custom_order_title': 'Custom Order',
      'custom_order_subtitle': 'Special service kekkalam',
      'broadband_title': 'Internet Bill',
      'broadband_subtitle': 'Internet service manage pannu',
      'mobile_puncture_title': 'Mobile Puncture',
      'mobile_puncture_subtitle': 'Vandi puncture repair on call',
      'pharmacy_title': 'Pharmacy',
      'pharmacy_subtitle': 'Medicine delivery',
      'book_puncture': 'Puncture-ku book pannu?',
      'call_now': 'Call Now',
      'later': 'Apram',
      'service_coming_soon': 'Seekiram varudhu!',
      'language_label': 'Language',
      'home_label': 'Home',
      'chat_label': 'Live Rates',
      'rides_label': 'Play Zone',
      'account_label': 'Account',
      'my_rides_label': 'En rides',
      'live_rates_label': 'Live Rates',
      'play_zone_label': 'Play Zone',
      'live_label': 'Live',
      'erode_label': 'Erode, Tamil Nadu',
      'live_rates_title': 'Live Rates',
      'live_rates_subtitle':
          'Gold, silver, petrol rate ellam ore glance la paakalam.',
      'today_price_label': 'Innaiku rate',
      'play_zone_title': 'Play Zone',
      'play_zone_subtitle':
          'NJ TECH 3x3 puzzle solve panni unga best time beat pannunga.',
      'sliding_puzzle_title': 'Sarukkum Puthir Vilayattu',
      'moves_label': 'Moves',
      'time_label': 'Time',
      'reset_label': 'Reset',
      'play_again_label': 'Play Again',
      'puzzle_instruction':
          'NJ TECH um Erode pattern pieces um straight ah align pannunga.',
      'solved_title': 'Neenga theerthuttinga!',
      'solved_message_intro': 'Semma moves!',
      'bike_label': 'Bike',
      'auto_label': 'Auto',
      'cab_label': 'Cab',
      'parcel_label': 'Parcel',
      'mini_truck_label': 'Mini Truck',
      'lorry_label': 'Lorry',
      'emergency_manpower_label': 'SOS',
      'where_to_go_hint': 'Enga poganum?',
      'choose_vehicle_label': 'Vehicle choose pannu',
      'distance_label': 'Distance',
      'eta_label': 'ETA',
      'choose_destination_title': 'Destination choose pannu',
      'update_pickup_title': 'Pickup update pannu',
      'drag_map_hint':
          'Erode la place find panna map drag pannunga illa 3 letters type pannunga.',
      'pickup_location_label': 'Pickup location',
      'drop_destination_label': 'Drop destination',
      'drop_pin_destination_title': 'Destination-ku pin podu',
      'drop_pin_pickup_title': 'Pickup-ku pin podu',
      'finding_street_label': 'Exact street address theduthu irukom...',
      'move_map_to_select_label': 'Select panna map move pannunga',
      'use_as_destination_label': 'Destination ah use pannu',
      'use_as_pickup_label': 'Pickup ah use pannu',
      'pay_via_soundbox': 'Paytm soundbox la bill kattru',
      'scan_soundbox_qr': 'Soundbox QR scan pannitu, amount pay pannitu confirm pannu.',
      'awaiting_hero_payment': 'Hero confirmation ku waiting...',
      'scan_and_wait_hero': 'Paytm Soundbox scan pannitu, Hero unga bill confirm panna vara wait pannu.',
      'open_upi_scan_soundbox': 'UPI la Paytm open pannu, Hero Soundbox scan pannu, exact bill amount pay pannu.',
      'hero_booking_mega_title': 'Hero Booking',
      'hero_booking_mega_subtitle': 'Yenna vela irunthalum Hero-a book pannunga',
      'taxi_mega_title': 'Taxi & Transport',
      'taxi_mega_subtitle': 'Bike, Auto, Cab, Parcel & Rent',
      'food_mega_subtitle': 'Erode la ethachum shop-la irunthu order pannunga!',
      'grocery_mega_title': 'Grocery Order',
      'grocery_mega_subtitle': 'Unga list type pannunga illa photo eduthu anuppunga',
      'electronics_mega_title': 'Electronic Services',
      'electronics_mega_subtitle': 'Mobile, Laptop, PC, CCTV, TV & AC',
      'mobiles_mega_title': 'Mobiles',
      'mobiles_mega_subtitle': 'New & used phones, repair, best offers',
      'carservice_mega_title': 'Car Service & Wash',
      'carservice_mega_subtitle': 'Water wash, repair & old spares',
      'construction_mega_title': 'Construction & Building',
      'construction_mega_subtitle': 'Usha Constructions, contracts & plans',
      'electrician_mega_title': 'Electrician',
      'electrician_mega_subtitle': 'Wiring, switchboard & appliance faults',
      'puncture_mega_title': 'Puncture / Tyre',
      'puncture_mega_subtitle': 'Flat tyre or air top-up, tracked live',
      'internet_mega_title': 'Internet & Broadband',
      'internet_mega_subtitle': 'Fast recharge plans & broadband deals',
      'printing_mega_title': 'Designing & Printing',
      'printing_mega_subtitle': 'Visiting card, flex, bill book & notice',
      'eseva_mega_title': 'E-Seva Online Services',
      'eseva_mega_subtitle': 'PAN, Aadhaar, Passport, Voter ID & more',
      'hero_guide_title': 'Register panra vidham (3 steps)',
      'hero_guide_hint': 'Enna venum-nu paakka tap pannunga',
      'hero_guide_s1_title': 'Ungaloda details fill pannunga',
      'hero_guide_s1_body': 'Peyar, phone, DOB, address matrum ungaloda city. "Use my current location" use pannunga, illa city-a neengale select pannunga.',
      'hero_guide_s2_title': 'Ungaloda documents add pannunga',
      'hero_guide_s2_body': 'Driving License, Aadhaar matrum PAN — number kooda ovvondrukkum clear photo. Apparam nalla lighting-la oru live selfie edunga.',
      'hero_guide_s3_title': 'Submit panni approval-ku wait pannunga',
      'hero_guide_s3_body': 'Vehicle category select panni, SOS agreement accept panni, Submit pannunga. Admin verify panni call panuvanga — pothuva 2-4 hours-la.',
      'hero_guide_tip': 'Tip: start panradhukku munnadi ellaa documents-um ready-a vachukonga. Upload panradhula problem-a? Keela irukkura WhatsApp button use pannunga.',
      'otherservices_mega_title': 'Other Services',
      'otherservices_mega_subtitle': 'Broadband, mobile puncture & more',
      'other_internet_label': 'Internet',
      'other_puncture_label': 'Puncture',
      'other_cleaning_label': 'Cleaning',
      'other_electrician_label': 'Electrician',
      'greeting_hi': 'Hi',
      'greeting_morning': 'Kaalai Vanakkam',
      'greeting_afternoon': 'Madhiya Vanakkam',
      'greeting_evening': 'Malai Vanakkam',
      'greeting_night': 'Iravu Vanakkam',
      'food_hub_prompt': 'Enna order pannanum?',
      'food_hub_custom_subtitle': 'Erode la ethachum shop-la irunthu order pannunga',
      'food_hub_shops_heading': 'Unga favourite shops-la irunthu order pannunga',
      'food_hub_shops_subheading': 'Avanga site-la order pannunga pay pannunga — namma hero adha eduthu unga kitta kondu varuvaru.',
      'settings_title': 'Settings',
      'notifications_section': 'Notifications',
      'push_notifications_title': 'Push Notifications',
      'push_notifications_subtitle': 'Push notifications receive pannunga',
      'ride_alerts_title': 'Ride Alerts',
      'ride_alerts_subtitle': 'Unga rides pathi updates',
      'promotional_alerts_title': 'Promotional Alerts',
      'promotional_alerts_subtitle': 'Offers & deals',
      'preferences_section': 'Preferences',
      'location_services_title': 'Location Services',
      'location_services_subtitle': 'App location access panna anumathi kudunga',
      'biometric_login_title': 'Biometric Login',
      'biometric_login_subtitle': 'Quick login-ku fingerprint use pannunga',
      'dark_mode_title': 'Dark Mode',
      'dark_mode_subtitle': 'Dark theme ippo active ah irukku',
      'theme_title': 'Theme',
      'theme_subtitle': 'Unga favourite look ah select pannunga',
      'map_provider_section': 'Map Provider',
      'language_region_section': 'Language & Region',
      'privacy_security_section': 'Privacy & Security',
      'about_section': 'About',
      'language_picker_title': 'Language / Mozhi',
      'language_picker_subtitle': 'App text style select pannunga',
      'map_provider_info_title': 'Map Provider (Auto-Managed)',
      'map_provider_fallback': 'OpenStreetMap use pannuthu (Ola Maps kidaikala)',
      'map_provider_primary': 'Ola Maps use pannuthu (Primary)',
      'privacy_policy_title': 'Privacy Policy',
      'privacy_policy_subtitle': 'Namma privacy policy ah paakalam',
      'terms_title': 'Terms of Service',
      'terms_subtitle': 'Terms & conditions ah paakalam',
      'delete_account_title': 'Account Delete',
      'delete_account_subtitle': 'Unga account ah permanent ah delete pannunga',
      'rate_app_title': 'App-a Rate pannunga',
      'rate_app_subtitle': 'Play Store-la namma rate pannunga',
      'share_app_title': 'App-a Share pannunga',
      'share_app_subtitle': 'Friends-a invite pannunga',
      'help_support_title': 'Help & Support',
      'help_support_subtitle': 'Issues-ku help vaangunga',
      'share_link_copied_snack': 'Link copy aachu! Unga friends-kitta share pannunga.',
      'could_not_open_link_snack': 'Link open aagala',
      'app_version_name': 'Allin1 Super App',
      'app_version_number': 'Version 1.0.0 (Build 1)',
      'app_made_with_love': 'Erode la ❤️ oda banachadhu',
      'delete_account_dialog_title': 'Account Delete pannanuma?',
      'delete_account_dialog_body': 'Intha action ah undo panna mudiyathu. Unga ride history, saved address, payment methods ellame permanent ah delete aagum.',
      'cancel_label': 'Cancel',
      'delete_label': 'Delete',
      'delete_account_requested_snack': 'Account delete request pannirukeenga. Help-ku support-a contact pannunga.',
      'select_currency_title': 'Currency select pannunga',
      'currency_inr_name': 'Indian Rupee',
      'currency_usd_name': 'US Dollar',
      'currency_eur_name': 'Euro',
      'exit_app_title': 'App-a vittu poganuma?',
      'exit_app_body': 'Allin1-a moodalama?',
      'press_home_to_minimize': 'Minimize panna unga device oda Home button-a azhutthavum',
      'no_label': 'Illa',
      'yes_label': 'Aam',
      'nav_home_label': 'Home',
      'nav_rewards_label': 'Rewards',
      'nav_playzone_label': 'Play Zone',
      'nav_guru_label': 'Chitti AI',
      'nav_safety_label': 'Safety',
      'select_city_title': 'City select pannunga',
      'use_current_location_label': 'En current location use pannu',
      'featured_shop_badge': '★ Featured Shop',
      'shop_open_label': 'Open',
      'erode_fresh_name': 'Erode Fresh',
      'erode_fresh_subtitle': '★★  · Fresh groceries',
      'promo_free_ride_title': 'Unga first ride free!',
      'promo_free_ride_subtitle': 'Erode la enga venumnalum bike taxi book pannunga',
      'promo_book_label': 'Book pannu →',
      'promo_guru_title': '1 varusha Chitti AI subscription free ah vangunga',
      'promo_guru_badge': 'CHITTI',
      'promo_guru_subtitle': '1 varusha free Chitti AI offer-ku NJ TECH-a paarunga.',
      'drawer_my_profile': 'En profile',
      'drawer_activity': 'Activity',
      'drawer_settings': 'Settings',
      'drawer_help_whatsapp': 'Help & WhatsApp Support',
      'drawer_check_update': 'Update check pannu',
      'drawer_download_app_title': 'Turbo App-a download pannunga!',
      'drawer_download_app_subtitle': 'App vachi 10x fast ah use pannunga!',
      'drawer_sign_out': 'Sign Out / Logout',
      'app_version_footer': 'Allin1 Super App v1.0.0',
      'checking_updates_msg': 'Update check panniruken...',
      'app_updating_msg': 'Konjam wait pannunga, app update aguthu...',
      'up_to_date_title': 'Latest ah irukku',
      'up_to_date_body': 'App latest ah irukku!\nShorebird OTA moolama background updates run agudhu.',
      'got_it_label': 'Sari puriyuthu',
      'already_latest_version_snack': 'Neenga already latest version la than irukeenga',
      'welcome_new_version_title': 'Neenga ready!',
      'welcome_new_version_body': 'Allin1-oda latest version-ku welcome — pudhu fixes and features-a enjoy pannunga.',
      'updating_app_msg': 'App update aguthu...',
      'download_failed_title': 'Download start aganum',
      'download_failed_body': 'Unga browser direct download-a block pannirichu. Intha link-a copy pannu Chrome la open pannunga:',
      'copy_link_label': 'Link copy pannu',
      'close_label': 'Close',
      'link_copied_snack': 'Link copy ஆச்சு',
      'apk_sheet_title': '📲 NJ TECH Apps download pannunga',
      'download_customer_app_label': '🛒  Customer App download pannu',
      'download_hero_app_label': '🏍️  Hero App download pannu',
      'dismiss_label': 'Close pannu',
      'reload_tooltip': 'Reload',
      'opening_erode_fiber_msg': 'Erode Fiber open aguthu...',
      'erode_fiber_open_title': 'Erode Fiber open aayiduchu!',
      'erode_fiber_open_subtitle': 'Site app kulla load aayiduchu.',
      'back_to_dashboard_label': '← Dashboard-ku thirumbu',
      'could_not_open_inapp_title': 'App kulla open panna mudiyala',
      'check_internet_retry_subtitle': 'Internet check pannitu again try pannunga.',
      'try_again_label': 'Again try pannu',
      'daily_scratch_badge': '🎰 Scratch & Win',
      'scratch_reveal_hint': 'Unga gift paakka scratch pannunga!',
      'scratch_reward_title': 'Neenga oru Paytm Soundbox win pannitinga!',
      'scratch_reward_subtitle': 'Unga reward vaanga keela tap pannunga',
      'scratch_revealed_label': '🎊 Reveal ஆச்சு!',
      'scratch_keep_going_label': 'Scratch panni konde iru...',
      'call_to_claim_label': '📞 Vaanga call pannunga',
      'update_badge_label': 'UPDATE',
      'category_taxi_slide': '🚕 Taxi & Transport',
      'category_food_slide': '🍔 Food Delivery',
      'category_grocery_slide': '🛒 Groceries',
      'category_services_slide': '🔧 Services',
      'downloading_update_snack': 'Update download aguthu...',
      'promo_firstride_title': 'First Ride FREE 🛵',
      'promo_firstride_subtitle': 'Pudhu user ah? Unga first taxi ride namma treat!',
      'promo_book_now_label': 'Ippo Book Pannu',
      'promo_new_users_label': 'Pudhu Users',
      'promo_claimed_label': 'Vaangiyaachu ✓',
      'tour_welcome_title': 'Allin1-ku Welcome! 👋',
      'tour_welcome_desc': 'Erode-ku venum ellame ore app la — bike taxi, food delivery, grocery, tech store innum pala. Basics quick ah paakalama?',
      'tour_home_desc': 'Taxi book pannu, food/grocery order pannu, illa special service kekalam — ellame inga irunthe.',
      'tour_rewards_desc': 'Free Paytm box illa Chitti AI subscription mari real rewards vaanga quick quiz answer pannu.',
      'tour_playzone_desc': 'Unga ride illa order-ku wait pannum bothu 2048, Whack-a-Mole mari quick games vilayadu.',
      'tour_guru_desc': 'Unga AI assistant — booking, tracking illa app pathi enna venumnalum kelu.',
      'tour_safety_desc': 'Venum bothu real safety-ku one-tap SOS emergency help.',
      'eseva_xerox': 'Xerox & Colour Printout',
      'eseva_voter_id': 'Voter ID Card',
      'eseva_pan': 'PAN Card',
      'eseva_aadhaar': 'Aadhaar Card Update',
      'eseva_rental': 'Rental Agreement & Job Typing',
      'eseva_employment': 'Velaivaippu Pathivu',
      'eseva_ration': 'Ration Card',
      'eseva_birth_death': 'Birth / Death Certificate',
      'eseva_fssai_msme': 'FSSAI / MSME Certificate',
      'eseva_certificate': 'Income, Nativity & Community Certificate',
      'eseva_ayushman': 'Ayushman Card',
      'eseva_eshram': 'E-Shram Card',
      'eseva_laptop': 'Laptop, Computer Sales & Service',
      'eseva_photo_print': 'Photo Print',
      'eseva_pvc': 'PVC Plastic Card Print',
    },
    // FIX (Nizam's language request): added Hindi as the 4th supported
    // language, keyed off the SAME keys as en/ta/tg so every existing
    // t('key') call site automatically gains Hindi support with zero
    // other code changes.
    'hi': {
      'app_title': 'my allin1',
      'greeting': 'नमस्ते',
      'what_need_today': 'आज आपको क्या चाहिए?',
      'bike_taxi_title': 'बाइक टैक्सी',
      'bike_taxi_subtitle': 'ईरोड में तेज़ सवारी',
      'food_delivery_title': 'फ़ूड डिलीवरी',
      'food_delivery_subtitle': '16वीं रोड की खासियतें',
      'grocery_title': 'किराना',
      'grocery_subtitle': 'ताज़ा और तेज़',
      'tech_store_title': 'टेक स्टोर',
      'tech_store_subtitle': 'NJ TECH गैजेट्स',
      'custom_order_title': 'कस्टम ऑर्डर',
      'custom_order_subtitle': 'खास सेवा के लिए पूछें',
      'broadband_title': 'ब्रॉडबैंड / वाईफाई',
      'broadband_subtitle': 'अपनी इंटरनेट सेवा प्रबंधित करें',
      'mobile_puncture_title': 'मोबाइल पंक्चर',
      'mobile_puncture_subtitle': 'तुरंत पंक्चर मरम्मत',
      'pharmacy_title': 'फार्मेसी',
      'pharmacy_subtitle': 'दवाइयाँ घर पहुंचाई जाएंगी',
      'book_puncture': 'पंक्चर के लिए बुक करें?',
      'call_now': 'अभी कॉल करें',
      'later': 'बाद में',
      'service_coming_soon': 'जल्द ही आ रहा है!',
      'language_label': 'भाषा',
      'home_label': 'होम',
      'chat_label': 'लाइव रेट्स',
      'rides_label': 'प्ले ज़ोन',
      'account_label': 'खाता',
      'my_rides_label': 'मेरी सवारियाँ',
      'live_rates_label': 'लाइव रेट्स',
      'play_zone_label': 'प्ले ज़ोन',
      'live_label': 'लाइव',
      'erode_label': 'ईरोड, तमिलनाडु',
      'live_rates_title': 'लाइव रेट्स',
      'live_rates_subtitle':
          'ईरोड के लिए सोना, चांदी और पेट्रोल की कीमतें एक ही नज़र में।',
      'today_price_label': 'आज की कीमत',
      'play_zone_title': 'प्ले ज़ोन',
      'play_zone_subtitle':
          'NJ TECH 3x3 पहेली हल करें और अपना सबसे अच्छा समय हराएं।',
      'sliding_puzzle_title': 'स्लाइडिंग पज़ल गेम',
      'moves_label': 'चालें',
      'time_label': 'समय',
      'reset_label': 'रीसेट',
      'play_again_label': 'फिर से खेलें',
      'puzzle_instruction':
          'NJ TECH और ईरोड के पैटर्न टुकड़ों को सही तरीके से मिलाएं।',
      'solved_title': 'आपने हल कर लिया!',
      'solved_message_intro': 'शानदार चालें!',
      'bike_label': 'बाइक',
      'auto_label': 'ऑटो',
      'cab_label': 'कैब',
      'parcel_label': 'पार्सल',
      'mini_truck_label': 'मिनी ट्रक',
      'lorry_label': 'लॉरी',
      'emergency_manpower_label': 'एसओएस',
      'where_to_go_hint': 'आप कहाँ जाना चाहते हैं?',
      'choose_vehicle_label': 'वाहन चुनें',
      'distance_label': 'दूरी',
      'eta_label': 'ईटीए',
      'choose_destination_title': 'गंतव्य चुनें',
      'update_pickup_title': 'पिकअप अपडेट करें',
      'drag_map_hint':
          'ईरोड में जगह खोजने के लिए मैप खींचें या 3 अक्षर टाइप करें।',
      'pickup_location_label': 'पिकअप स्थान',
      'drop_destination_label': 'ड्रॉप गंतव्य',
      'drop_pin_destination_title': 'गंतव्य के लिए पिन लगाएं',
      'drop_pin_pickup_title': 'पिकअप के लिए पिन लगाएं',
      'finding_street_label': 'सही सड़क का पता खोजा जा रहा है...',
      'move_map_to_select_label': 'चुनने के लिए मैप को हिलाएं',
      'use_as_destination_label': 'गंतव्य के रूप में उपयोग करें',
      'use_as_pickup_label': 'पिकअप के रूप में उपयोग करें',
      'pay_via_soundbox': 'Paytm साउंडबॉक्स से बिल भरें',
      'scan_soundbox_qr': 'फिजिकल साउंडबॉक्स QR स्कैन करें और भुगतान होने पर पुष्टि करें।',
      'awaiting_hero_payment': 'हीरो की पुष्टि का इंतज़ार है...',
      'scan_and_wait_hero': 'कृपया Paytm साउंडबॉक्स स्कैन करें और हीरो द्वारा आपके बिल की पुष्टि होने तक प्रतीक्षा करें।',
      'open_upi_scan_soundbox': 'UPI चूज़र से Paytm खोलें, हीरो का Paytm साउंडबॉक्स स्कैन करें, और सही बिल राशि पूरी करें।',
      'hero_booking_mega_title': 'हीरो बुकिंग',
      'hero_booking_mega_subtitle': 'किसी भी काम या डिलीवरी के लिए हीरो बुक करें',
      'taxi_mega_title': 'टैक्सी और परिवहन',
      'taxi_mega_subtitle': 'बाइक, ऑटो, कैब, पार्सल और किराया',
      'food_mega_subtitle': 'ईरोड की किसी भी दुकान से ऑर्डर करें!',
      'grocery_mega_title': 'किराना ऑर्डर',
      'grocery_mega_subtitle': 'अपनी लिस्ट टाइप करें या फोटो खींचें',
      'electronics_mega_title': 'इलेक्ट्रॉनिक सेवाएं',
      'electronics_mega_subtitle': 'मोबाइल, लैपटॉप, पीसी, सीसीटीवी, टीवी और एसी',
      'mobiles_mega_title': 'मोबाइल',
      'mobiles_mega_subtitle': 'नए और पुराने फोन, रिपेयर, बेहतरीन ऑफर',
      'carservice_mega_title': 'कार सर्विस और वॉश',
      'carservice_mega_subtitle': 'वॉटर वॉश, मरम्मत और पुराने पुर्जे',
      'construction_mega_title': 'निर्माण और बिल्डिंग',
      'construction_mega_subtitle': 'उषा कंस्ट्रक्शन्स, अनुबंध और योजनाएं',
      'electrician_mega_title': 'इलेक्ट्रीशियन',
      'electrician_mega_subtitle': 'वायरिंग, स्विचबोर्ड और उपकरण खराबी',
      'puncture_mega_title': 'पंचर / टायर',
      'puncture_mega_subtitle': 'फ्लैट टायर या हवा भरना, लाइव ट्रैकिंग',
      'internet_mega_title': 'इंटरनेट और ब्रॉडबैंड',
      'internet_mega_subtitle': 'तेज़ रिचार्ज प्लान और ब्रॉडबैंड ऑफर',
      'printing_mega_title': 'डिज़ाइनिंग और प्रिंटिंग',
      'printing_mega_subtitle': 'विज़िटिंग कार्ड, फ्लेक्स, बिल बुक और नोटिस',
      'eseva_mega_title': 'ई-सेवा ऑनलाइन सेवाएं',
      'eseva_mega_subtitle': 'पैन, आधार, पासपोर्ट, वोटर आईडी और अधिक',
      'hero_guide_title': 'पंजीकरण कैसे करें (3 चरण)',
      'hero_guide_hint': 'क्या चाहिए यह देखने के लिए टैप करें',
      'hero_guide_s1_title': 'अपना विवरण भरें',
      'hero_guide_s1_body': 'नाम, फ़ोन, जन्म तिथि, पता और आपका शहर। "मेरा वर्तमान स्थान" का उपयोग करें, या शहर स्वयं चुनें।',
      'hero_guide_s2_title': 'अपने दस्तावेज़ जोड़ें',
      'hero_guide_s2_body': 'ड्राइविंग लाइसेंस, आधार और पैन — नंबर के साथ हर एक की साफ़ फ़ोटो। फिर अच्छी रोशनी में एक लाइव सेल्फ़ी लें।',
      'hero_guide_s3_title': 'जमा करें और स्वीकृति की प्रतीक्षा करें',
      'hero_guide_s3_body': 'अपना वाहन प्रकार चुनें, SOS समझौता स्वीकार करें, फिर सबमिट करें। व्यवस्थापक सत्यापित करके आपको कॉल करेंगे — आमतौर पर 2-4 घंटे में।',
      'hero_guide_tip': 'सुझाव: शुरू करने से पहले सभी दस्तावेज़ तैयार रखें। अपलोड में परेशानी? नीचे दिए WhatsApp बटन का उपयोग करें।',
      'otherservices_mega_title': 'अन्य सेवाएं',
      'otherservices_mega_subtitle': 'ब्रॉडबैंड, मोबाइल पंक्चर और अधिक',
      'other_internet_label': 'इंटरनेट',
      'other_puncture_label': 'पंक्चर',
      'other_cleaning_label': 'सफाई',
      'other_electrician_label': 'इलेक्ट्रीशियन',
      'greeting_hi': 'नमस्ते',
      'greeting_morning': 'सुप्रभात',
      'greeting_afternoon': 'शुभ दोपहर',
      'greeting_evening': 'शुभ संध्या',
      'greeting_night': 'शुभ रात्रि',
      'food_hub_prompt': 'आप क्या ऑर्डर करना चाहेंगे?',
      'food_hub_custom_subtitle': 'ईरोड की किसी भी दुकान से ऑर्डर करें',
      'food_hub_shops_heading': 'अपनी पसंदीदा दुकानों से ऑर्डर करें',
      'food_hub_shops_subheading': 'उनकी साइट पर ऑर्डर करें और भुगतान करें — हमारा हीरो उसे लेकर आपके पास पहुंचाएगा।',
      'settings_title': 'सेटिंग्स',
      'notifications_section': 'सूचनाएं',
      'push_notifications_title': 'पुश नोटिफिकेशन',
      'push_notifications_subtitle': 'पुश नोटिफिकेशन प्राप्त करें',
      'ride_alerts_title': 'सवारी अलर्ट',
      'ride_alerts_subtitle': 'अपनी सवारियों के बारे में अपडेट पाएं',
      'promotional_alerts_title': 'प्रचार अलर्ट',
      'promotional_alerts_subtitle': 'ऑफ़र और डील्स',
      'preferences_section': 'प्राथमिकताएं',
      'location_services_title': 'लोकेशन सेवाएं',
      'location_services_subtitle': 'ऐप को लोकेशन एक्सेस करने दें',
      'biometric_login_title': 'बायोमेट्रिक लॉगिन',
      'biometric_login_subtitle': 'तेज़ लॉगिन के लिए फिंगरप्रिंट का उपयोग करें',
      'dark_mode_title': 'डार्क मोड',
      'dark_mode_subtitle': 'डार्क थीम अभी सक्रिय है',
      'theme_title': 'थीम',
      'theme_subtitle': 'अपनी पसंदीदा लुक चुनें',
      'map_provider_section': 'मैप प्रोवाइडर',
      'language_region_section': 'भाषा और क्षेत्र',
      'privacy_security_section': 'गोपनीयता और सुरक्षा',
      'about_section': 'ऐप के बारे में',
      'language_picker_title': 'भाषा / Mozhi',
      'language_picker_subtitle': 'ऐप टेक्स्ट कैसा दिखे यह चुनें',
      'map_provider_info_title': 'मैप प्रोवाइडर (ऑटो-मैनेज्ड)',
      'map_provider_fallback': 'OpenStreetMap का उपयोग हो रहा है (Ola Maps उपलब्ध नहीं)',
      'map_provider_primary': 'Ola Maps का उपयोग हो रहा है (प्राइमरी)',
      'privacy_policy_title': 'गोपनीयता नीति',
      'privacy_policy_subtitle': 'हमारी गोपनीयता नीति देखें',
      'terms_title': 'सेवा की शर्तें',
      'terms_subtitle': 'नियम और शर्तें देखें',
      'delete_account_title': 'खाता हटाएं',
      'delete_account_subtitle': 'अपना खाता स्थायी रूप से हटाएं',
      'rate_app_title': 'ऐप को रेट करें',
      'rate_app_subtitle': 'Play Store पर हमें रेट करें',
      'share_app_title': 'ऐप शेयर करें',
      'share_app_subtitle': 'दोस्तों को जोड़ने के लिए आमंत्रित करें',
      'help_support_title': 'सहायता और समर्थन',
      'help_support_subtitle': 'समस्याओं में सहायता प्राप्त करें',
      'share_link_copied_snack': 'लिंक कॉपी हो गया! अपने दोस्तों के साथ शेयर करें।',
      'could_not_open_link_snack': 'लिंक नहीं खुल सका',
      'app_version_name': 'Allin1 सुपर ऐप',
      'app_version_number': 'वर्शन 1.0.0 (बिल्ड 1)',
      'app_made_with_love': 'ईरोड में ❤️ के साथ बनाया गया',
      'delete_account_dialog_title': 'खाता हटाएं?',
      'delete_account_dialog_body': 'यह कार्रवाई पूर्ववत नहीं की जा सकती। आपका राइड इतिहास, सहेजे गए पते और भुगतान विधियों सहित सभी डेटा स्थायी रूप से हटा दिया जाएगा।',
      'cancel_label': 'रद्द करें',
      'delete_label': 'हटाएं',
      'delete_account_requested_snack': 'खाता हटाने का अनुरोध किया गया। सहायता के लिए संपर्क करें।',
      'select_currency_title': 'मुद्रा चुनें',
      'currency_inr_name': 'भारतीय रुपया',
      'currency_usd_name': 'अमेरिकी डॉलर',
      'currency_eur_name': 'यूरो',
      'exit_app_title': 'ऐप छोड़ें?',
      'exit_app_body': 'Allin1 बंद करें?',
      'press_home_to_minimize': 'मिनिमाइज़ करने के लिए अपने डिवाइस का Home बटन दबाएं',
      'no_label': 'नहीं',
      'yes_label': 'हाँ',
      'nav_home_label': 'होम',
      'nav_rewards_label': 'रिवॉर्ड्स',
      'nav_playzone_label': 'प्ले ज़ोन',
      'nav_guru_label': 'चिट्टी AI',
      'nav_safety_label': 'सुरक्षा',
      'select_city_title': 'शहर चुनें',
      'use_current_location_label': 'मेरा वर्तमान स्थान उपयोग करें',
      'featured_shop_badge': '★ फीचर्ड शॉप',
      'shop_open_label': 'खुला है',
      'erode_fresh_name': 'इरोड फ्रेश',
      'erode_fresh_subtitle': '★★  · ताज़ा किराना सामान',
      'promo_free_ride_title': 'आपकी पहली राइड फ्री है!',
      'promo_free_ride_subtitle': 'इरोड में कहीं भी बाइक टैक्सी बुक करें',
      'promo_book_label': 'बुक करें →',
      'promo_guru_title': '1 साल की चिट्टी AI सदस्यता मुफ्त पाएं',
      'promo_guru_badge': 'चिट्टी',
      'promo_guru_subtitle': '1 साल का मुफ्त चिट्टी AI ऑफर पाने के लिए NJ TECH पर जाएं।',
      'drawer_my_profile': 'मेरी प्रोफाइल',
      'drawer_activity': 'गतिविधि',
      'drawer_settings': 'सेटिंग्स',
      'drawer_help_whatsapp': 'सहायता और WhatsApp सपोर्ट',
      'drawer_check_update': 'अपडेट जांचें',
      'drawer_download_app_title': 'टर्बो ऐप डाउनलोड करें!',
      'drawer_download_app_subtitle': 'ऐप पाएं और 10x तेज़ चलाएं!',
      'drawer_sign_out': 'साइन आउट / लॉगआउट',
      'app_version_footer': 'Allin1 सुपर ऐप v1.0.0',
      'checking_updates_msg': 'अपडेट जांचे जा रहे हैं...',
      'app_updating_msg': 'कृपया प्रतीक्षा करें, ऐप अपडेट हो रहा है...',
      'up_to_date_title': 'अप टू डेट',
      'up_to_date_body': 'ऐप अप टू डेट है!\nShorebird OTA के ज़रिए बैकग्राउंड अपडेट सक्रिय हैं।',
      'got_it_label': 'समझ गया',
      'already_latest_version_snack': 'आप पहले से ही नवीनतम संस्करण पर हैं',
      'welcome_new_version_title': 'आप तैयार हैं!',
      'welcome_new_version_body': 'Allin1 के नवीनतम संस्करण में आपका स्वागत है — नई सुविधाओं और सुधारों का आनंद लें।',
      'updating_app_msg': 'ऐप अपडेट हो रहा है...',
      'download_failed_title': 'डाउनलोड शुरू नहीं हो सका',
      'download_failed_body': 'आपके ब्राउज़र ने सीधे डाउनलोड को ब्लॉक कर दिया। इस लिंक को कॉपी करके Chrome में खोलें:',
      'copy_link_label': 'लिंक कॉपी करें',
      'close_label': 'बंद करें',
      'link_copied_snack': 'लिंक कॉपी हो गया',
      'apk_sheet_title': '📲 NJ TECH ऐप्स डाउनलोड करें',
      'download_customer_app_label': '🛒  कस्टमर ऐप डाउनलोड करें',
      'download_hero_app_label': '🏍️  हीरो ऐप डाउनलोड करें',
      'dismiss_label': 'बंद करें',
      'reload_tooltip': 'रीलोड करें',
      'opening_erode_fiber_msg': 'इरोड फाइबर खुल रहा है...',
      'erode_fiber_open_title': 'इरोड फाइबर खुल गया है!',
      'erode_fiber_open_subtitle': 'साइट ऐप के अंदर ही लोड हो गई।',
      'back_to_dashboard_label': '← डैशबोर्ड पर वापस जाएं',
      'could_not_open_inapp_title': 'ऐप के अंदर खोला नहीं जा सका',
      'check_internet_retry_subtitle': 'इंटरनेट जांचें और फिर से कोशिश करें।',
      'try_again_label': 'फिर कोशिश करें',
      'daily_scratch_badge': '🎰 स्क्रैच करें और जीतें',
      'scratch_reveal_hint': 'अपना गिफ्ट देखने के लिए स्क्रैच करें!',
      'scratch_reward_title': 'आपने एक Paytm साउंडबॉक्स जीता है!',
      'scratch_reward_subtitle': 'अपना इनाम पाने के लिए नीचे टैप करें',
      'scratch_revealed_label': '🎊 खुल गया!',
      'scratch_keep_going_label': 'स्क्रैच करते रहें...',
      'call_to_claim_label': '📞 पाने के लिए कॉल करें',
      'update_badge_label': 'अपडेट',
      'category_taxi_slide': '🚕 टैक्सी और परिवहन',
      'category_food_slide': '🍔 फूड डिलीवरी',
      'category_grocery_slide': '🛒 किराना',
      'category_services_slide': '🔧 सेवाएं',
      'downloading_update_snack': 'अपडेट डाउनलोड हो रहा है...',
      'promo_firstride_title': 'पहली राइड फ्री 🛵',
      'promo_firstride_subtitle': 'नए यूज़र हैं? आपकी पहली टैक्सी राइड हमारी तरफ से!',
      'promo_book_now_label': 'अभी बुक करें',
      'promo_new_users_label': 'नए यूज़र्स',
      'promo_claimed_label': 'प्राप्त किया ✓',
      'tour_welcome_title': 'Allin1 में आपका स्वागत है! 👋',
      'tour_welcome_desc': 'इरोड की हर ज़रूरत एक ही ऐप में — बाइक टैक्सी, फूड डिलीवरी, किराना, टेक स्टोर और भी बहुत कुछ। बेसिक्स का जल्दी टूर लें?',
      'tour_home_desc': 'टैक्सी बुक करें, खाना/किराना ऑर्डर करें, या कोई खास सेवा मांगें — सब कुछ यहीं से।',
      'tour_rewards_desc': 'मुफ्त Paytm बॉक्स या चिट्टी AI सदस्यता जैसे असली इनाम पाने के लिए जल्दी क्विज़ का जवाब दें।',
      'tour_playzone_desc': 'अपनी राइड या ऑर्डर का इंतज़ार करते हुए 2048, Whack-a-Mole जैसे मज़ेदार गेम खेलें।',
      'tour_guru_desc': 'आपका AI असिस्टेंट — बुकिंग, ट्रैकिंग या ऐप के बारे में कुछ भी पूछें।',
      'tour_safety_desc': 'ज़रूरत पड़ने पर असली सुरक्षा के लिए वन-टैप SOS इमरजेंसी मदद।',
      'eseva_xerox': 'जेरोक्स और कलर प्रिंटआउट',
      'eseva_voter_id': 'वोटर आईडी कार्ड',
      'eseva_pan': 'पैन कार्ड',
      'eseva_aadhaar': 'आधार कार्ड अपडेट',
      'eseva_rental': 'रेंटल एग्रीमेंट और जॉब टाइपिंग',
      'eseva_employment': 'रोजगार पंजीकरण',
      'eseva_ration': 'राशन कार्ड',
      'eseva_birth_death': 'जन्म और मृत्यु प्रमाण पत्र',
      'eseva_fssai_msme': 'FSSAI / MSME / UDYAM',
      'eseva_certificate': 'आय, मूल निवासी और जाति प्रमाण पत्र',
      'eseva_ayushman': 'आयुष्मान कार्ड',
      'eseva_eshram': 'ई-श्रम कार्ड',
      'eseva_laptop': 'लैपटॉप और कंप्यूटर सेल्स/सर्विस',
      'eseva_photo_print': 'फोटो प्रिंट',
      'eseva_pvc': 'पीवीसी प्लास्टिक कार्ड प्रिंट',
    },
    // FIX (Nizam's i18n request): added Malayalam as the 5th supported
    // language, keyed off the SAME keys as en/ta/tg/hi so every existing
    // t('key') call site automatically gains Malayalam support with zero
    // other code changes.
    'ml': {
      'app_title': 'my allin1',
      'greeting': 'നമസ്കാരം',
      'what_need_today': 'ഇന്ന് നിങ്ങൾക്ക് എന്ത് വേണം?',
      'bike_taxi_title': 'ബൈക്ക് ടാക്സി',
      'bike_taxi_subtitle': 'ஈரோட്ടിൽ വേഗതയേറിയ യാത്ര',
      'food_delivery_title': 'ഫുഡ് ഡെലിവറി',
      'food_delivery_subtitle': '16-ാം റോഡ് സ്പെഷ്യൽസ്',
      'grocery_title': 'പലചരക്ക്',
      'grocery_subtitle': 'പുതിയതും വേഗതയേറിയതും',
      'tech_store_title': 'ടെക് സ്റ്റോർ',
      'tech_store_subtitle': 'NJ TECH ഗാഡ്ജെറ്റുകൾ',
      'custom_order_title': 'കസ്റ്റം ഓർഡർ',
      'custom_order_subtitle': 'പ്രത്യേക സേവനത്തിന് ചോദിക്കൂ',
      'broadband_title': 'ബ്രോഡ്ബാൻഡ് / വൈഫൈ',
      'broadband_subtitle': 'നിങ്ങളുടെ ഇന്റർനെറ്റ് സേവനം മാനേജ് ചെയ്യുക',
      'mobile_puncture_title': 'മൊബൈൽ പഞ്ചർ',
      'mobile_puncture_subtitle': 'വേഗത്തിലുള്ള പഞ്ചർ റിപ്പയർ',
      'pharmacy_title': 'ഫാർമസി',
      'pharmacy_subtitle': 'മരുന്നുകൾ ഡെലിവർ ചെയ്യും',
      'book_puncture': 'പഞ്ചറിന് ബുക്ക് ചെയ്യണോ?',
      'call_now': 'ഇപ്പോൾ വിളിക്കൂ',
      'later': 'പിന്നീട്',
      'service_coming_soon': 'ഉടൻ വരുന്നു!',
      'language_label': 'ഭാഷ',
      'home_label': 'ഹോം',
      'chat_label': 'ലൈവ് റേറ്റ്സ്',
      'rides_label': 'പ്ലേ സോൺ',
      'account_label': 'അക്കൗണ്ട്',
      'my_rides_label': 'എന്റെ യാത്രകൾ',
      'live_rates_label': 'ലൈവ് റേറ്റ്സ്',
      'play_zone_label': 'പ്ലേ സോൺ',
      'live_label': 'ലൈവ്',
      'erode_label': 'ஈரோடு, தமிழ்நாடு',
      'live_rates_title': 'ലൈവ് റേറ്റ്സ്',
      'live_rates_subtitle':
          'ஈரோட്ടിലെ സ്വർണ്ണം, വെള്ളി, ഇന്ധന വിലകൾ ഒറ്റനോട്ടത്തിൽ.',
      'today_price_label': 'ഇന്നത്തെ വില',
      'play_zone_title': 'പ്ലേ സോൺ',
      'play_zone_subtitle':
          'NJ TECH 3x3 പസിൽ പരിഹരിച്ച് നിങ്ങളുടെ മികച്ച സമയം തകർക്കൂ.',
      'sliding_puzzle_title': 'സ്ലൈഡിംഗ് പസിൽ ഗെയിം',
      'moves_label': 'നീക്കങ്ങൾ',
      'time_label': 'സമയം',
      'reset_label': 'റീസെറ്റ്',
      'play_again_label': 'വീണ്ടും കളിക്കൂ',
      'puzzle_instruction':
          'NJ TECH, ஈரோடு പാറ്റേൺ പീസുകൾ കൃത്യമായി അലൈൻ ചെയ്യൂ.',
      'solved_title': 'നിങ്ങൾ പരിഹരിച്ചു!',
      'solved_message_intro': 'മികച്ച നീക്കങ്ങൾ!',
      'bike_label': 'ബൈക്ക്',
      'auto_label': 'ഓട്ടോ',
      'cab_label': 'കാബ്',
      'parcel_label': 'പാഴ്സൽ',
      'mini_truck_label': 'മിനി ട്രക്ക്',
      'lorry_label': 'ലോറി',
      'emergency_manpower_label': 'എസ്ഒഎസ്',
      'where_to_go_hint': 'നിങ്ങൾ എവിടേക്കാണ് പോകേണ്ടത്?',
      'choose_vehicle_label': 'വാഹനം തിരഞ്ഞെടുക്കൂ',
      'distance_label': 'ദൂരം',
      'eta_label': 'ETA',
      'choose_destination_title': 'ലക്ഷ്യസ്ഥാനം തിരഞ്ഞെടുക്കൂ',
      'update_pickup_title': 'പിക്കപ്പ് അപ്ഡേറ്റ് ചെയ്യൂ',
      'drag_map_hint':
          'ஈரோட്ടിൽ സ്ഥലം കണ്ടെത്താൻ മാപ്പ് വലിക്കുക അല്ലെങ്കിൽ 3 അക്ഷരങ്ങൾ ടൈപ്പ് ചെയ്യുക.',
      'pickup_location_label': 'പിക്കപ്പ് സ്ഥലം',
      'drop_destination_label': 'ഡ്രോപ്പ് ലക്ഷ്യസ്ഥാനം',
      'drop_pin_destination_title': 'ലക്ഷ്യസ്ഥാനത്തിന് പിൻ ഇടൂ',
      'drop_pin_pickup_title': 'പിക്കപ്പിന് പിൻ ഇടൂ',
      'finding_street_label': 'കൃത്യമായ തെരുവ് വിലാസം കണ്ടെത്തുന്നു...',
      'move_map_to_select_label': 'തിരഞ്ഞെടുക്കാൻ മാപ്പ് നീക്കൂ',
      'use_as_destination_label': 'ലക്ഷ്യസ്ഥാനമായി ഉപയോഗിക്കൂ',
      'use_as_pickup_label': 'പിക്കപ്പായി ഉപയോഗിക്കൂ',
      'pay_via_soundbox': 'Paytm സൗണ്ട്ബോക്സ് വഴി ബിൽ അടയ്ക്കൂ',
      'scan_soundbox_qr': 'സൗണ്ട്ബോക്സ് QR സ്കാൻ ചെയ്ത് പണം അടച്ചതിന് ശേഷം സ്ഥിരീകരിക്കൂ.',
      'awaiting_hero_payment': 'ഹീറോയുടെ സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു...',
      'scan_and_wait_hero': 'Paytm സൗണ്ട്ബോക്സ് സ്കാൻ ചെയ്ത് ഹീറോ നിങ്ങളുടെ ബിൽ സ്ഥിരീകരിക്കുന്നത് വരെ കാത്തിരിക്കൂ.',
      'open_upi_scan_soundbox': 'UPI ചൂസർ വഴി Paytm തുറന്ന്, ഹീറോയുടെ Paytm സൗണ്ട്ബോക്സ് സ്കാൻ ചെയ്ത്, കൃത്യമായ ബിൽ തുക പൂർത്തിയാക്കൂ.',
      'hero_booking_mega_title': 'ഹീറോ ബുക്കിംഗ്',
      'hero_booking_mega_subtitle': 'ഏത് ജോലിക്കും ഡെലിവറിക്കും ഒരു ഹീറോയെ ബുക്ക് ചെയ്യൂ',
      'taxi_mega_title': 'ടാക്സി & ട്രാൻസ്പോർട്ടേഷൻ',
      'taxi_mega_subtitle': 'ബൈക്ക്, ഓട്ടോ, കാബ്, പാഴ്സൽ & വാടക',
      'food_mega_subtitle': 'ஈரோட്ടിലെ ഏത് കടയിൽ നിന്നും ഓർഡർ ചെയ്യൂ!',
      'grocery_mega_title': 'പലചരക്ക് ഓർഡർ',
      'grocery_mega_subtitle': 'നിങ്ങളുടെ ലിസ്റ്റ് ടൈപ്പ് ചെയ്യൂ അല്ലെങ്കിൽ ഫോട്ടോ എടുക്കൂ',
      'electronics_mega_title': 'ഇലക്ട്രോണിക് സേവനങ്ങൾ',
      'electronics_mega_subtitle': 'മൊബൈൽ, ലാപ്ടോപ്, പിസി, സിസിടിവി, ടിവി & എസി',
      'mobiles_mega_title': 'മൊബൈലുകൾ',
      'mobiles_mega_subtitle': 'പുതിയ & പഴയ ഫോൺ, റിപ്പയർ, മികച്ച ഓഫർ',
      'carservice_mega_title': 'കാർ സർവീസ് & വാഷ്',
      'carservice_mega_subtitle': 'വാട്ടർ വാഷ്, റിപ്പയർ & പഴയ സ്പെയറുകൾ',
      'construction_mega_title': 'നിർമ്മാണം & ബിൽഡിംഗ്',
      'construction_mega_subtitle': 'ഉഷ കൺസ്ട്രക്ഷൻസ്, കരാറുകൾ & പ്ലാനുകൾ',
      'electrician_mega_title': 'ഇലക്ട്രീഷ്യൻ',
      'electrician_mega_subtitle': 'വയറിംഗ്, സ്വിച്ച്ബോർഡ് & ഉപകരണ തകരാറുകൾ',
      'puncture_mega_title': 'പഞ്ചർ / ടയർ',
      'puncture_mega_subtitle': 'ഫ്ലാറ്റ് ടയർ അല്ലെങ്കിൽ എയർ ടോപ്പ്-അപ്പ്, ലൈവ് ട്രാക്കിംഗ്',
      'internet_mega_title': 'ഇന്റർനെറ്റ് & ബ്രോഡ്ബാൻഡ്',
      'internet_mega_subtitle': 'വേഗതയേറിയ റീചാർജ് പ്ലാനുകൾ & ബ്രോഡ്ബാൻഡ് ഓഫറുകൾ',
      'printing_mega_title': 'ഡിസൈനിംഗ് & പ്രിന്റിംഗ്',
      'printing_mega_subtitle': 'വിസിറ്റിംഗ് കാർഡ്, ഫ്ലെക്സ്, ബിൽ ബുക്ക് & നോട്ടീസ്',
      'eseva_mega_title': 'ഇ-സേവാ ഓൺലൈൻ സേവനങ്ങൾ',
      'eseva_mega_subtitle': 'പാൻ, ആധാർ, പാസ്‌പോർട്ട്, വോട്ടർ ഐഡി & കൂടുതൽ',
      'hero_guide_title': 'എങ്ങനെ രജിസ്റ്റർ ചെയ്യാം (3 ഘട്ടങ്ങൾ)',
      'hero_guide_hint': 'എന്താണ് വേണ്ടതെന്ന് കാണാൻ ടാപ്പ് ചെയ്യുക',
      'hero_guide_s1_title': 'നിങ്ങളുടെ വിവരങ്ങൾ പൂരിപ്പിക്കുക',
      'hero_guide_s1_body': 'പേര്, ഫോൺ, ജനനത്തീയതി, വിലാസം, നിങ്ങളുടെ നഗരം. "എന്റെ നിലവിലെ ലൊക്കേഷൻ" ഉപയോഗിക്കുക, അല്ലെങ്കിൽ നഗരം സ്വയം തിരഞ്ഞെടുക്കുക.',
      'hero_guide_s2_title': 'നിങ്ങളുടെ രേഖകൾ ചേർക്കുക',
      'hero_guide_s2_body': 'ഡ്രൈവിംഗ് ലൈസൻസ്, ആധാർ, പാൻ — നമ്പറും ഓരോന്നിന്റെയും വ്യക്തമായ ഫോട്ടോയും. പിന്നെ നല്ല വെളിച്ചത്തിൽ ഒരു ലൈവ് സെൽഫി എടുക്കുക.',
      'hero_guide_s3_title': 'സമർപ്പിച്ച് അംഗീകാരത്തിനായി കാത്തിരിക്കുക',
      'hero_guide_s3_body': 'വാഹന വിഭാഗം തിരഞ്ഞെടുത്ത്, SOS കരാർ അംഗീകരിച്ച്, സമർപ്പിക്കുക. അഡ്മിൻ പരിശോധിച്ച് നിങ്ങളെ വിളിക്കും — സാധാരണയായി 2-4 മണിക്കൂറിനുള്ളിൽ.',
      'hero_guide_tip': 'നുറുങ്ങ്: തുടങ്ങുന്നതിന് മുമ്പ് എല്ലാ രേഖകളും തയ്യാറാക്കി വയ്ക്കുക. അപ്‌ലോഡ് ചെയ്യാൻ ബുദ്ധിമുട്ടാണോ? താഴെയുള്ള WhatsApp ബട്ടൺ ഉപയോഗിക്കുക.',
      'otherservices_mega_title': 'മറ്റ് സേവനങ്ങൾ',
      'otherservices_mega_subtitle': 'ബ്രോഡ്ബാൻഡ്, മൊബൈൽ പഞ്ചർ & കൂടുതൽ',
      'other_internet_label': 'ഇന്റർനെറ്റ്',
      'other_puncture_label': 'പഞ്ചർ',
      'other_cleaning_label': 'ക്ലീനിംഗ്',
      'other_electrician_label': 'ഇലക്ട്രീഷ്യൻ',
      'greeting_hi': 'ഹായ്',
      'greeting_morning': 'സുപ്രഭാതം',
      'greeting_afternoon': 'ശുഭ മധ്യാഹ്നം',
      'greeting_evening': 'ശുഭ സന്ധ്യ',
      'greeting_night': 'ശുഭ രാത്രി',
      'food_hub_prompt': 'നിങ്ങൾക്ക് എന്താണ് ഓർഡർ ചെയ്യേണ്ടത്?',
      'food_hub_custom_subtitle': 'ஈரோட்டിലെ ഏത് കടയിൽ നിന്നും ഓർഡർ ചെയ്യൂ',
      'food_hub_shops_heading': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട കടകളിൽ നിന്ന് ഓർഡർ ചെയ്യൂ',
      'food_hub_shops_subheading': 'അവരുടെ സൈറ്റിൽ ഓർഡർ ചെയ്ത് പണം അടയ്ക്കൂ — ഞങ്ങളുടെ ഹീറോ അത് എടുത്ത് നിങ്ങൾക്ക് എത്തിക്കും.',
      'settings_title': 'സെറ്റിംഗ്സ്',
      'notifications_section': 'അറിയിപ്പുകൾ',
      'push_notifications_title': 'പുഷ് അറിയിപ്പുകൾ',
      'push_notifications_subtitle': 'പുഷ് അറിയിപ്പുകൾ സ്വീകരിക്കൂ',
      'ride_alerts_title': 'റൈഡ് അലേർട്ടുകൾ',
      'ride_alerts_subtitle': 'നിങ്ങളുടെ യാത്രകളെക്കുറിച്ചുള്ള അപ്ഡേറ്റുകൾ നേടൂ',
      'promotional_alerts_title': 'പ്രമോഷണൽ അലേർട്ടുകൾ',
      'promotional_alerts_subtitle': 'ഓഫറുകളും ഡീലുകളും',
      'preferences_section': 'മുൻഗണനകൾ',
      'location_services_title': 'ലൊക്കേഷൻ സേവനങ്ങൾ',
      'location_services_subtitle': 'ആപ്പിന് ലൊക്കേഷൻ ആക്സസ് ചെയ്യാൻ അനുവദിക്കൂ',
      'biometric_login_title': 'ബയോമെട്രിക് ലോഗിൻ',
      'biometric_login_subtitle': 'വേഗത്തിലുള്ള ലോഗിനായി ഫിംഗർപ്രിന്റ് ഉപയോഗിക്കൂ',
      'dark_mode_title': 'ഡാർക്ക് മോഡ്',
      'dark_mode_subtitle': 'ഡാർക്ക് തീം നിലവിൽ സജീവമാണ്',
      'theme_title': 'തീം',
      'theme_subtitle': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ലുക്ക് തിരഞ്ഞെടുക്കൂ',
      'map_provider_section': 'മാപ്പ് പ്രൊവൈഡർ',
      'language_region_section': 'ഭാഷയും പ്രദേശവും',
      'privacy_security_section': 'സ്വകാര്യതയും സുരക്ഷയും',
      'about_section': 'ആപ്പിനെക്കുറിച്ച്',
      'language_picker_title': 'ഭാഷ / Mozhi',
      'language_picker_subtitle': 'ആപ്പ് ടെക്സ്റ്റ് എങ്ങനെ കാണണമെന്ന് തിരഞ്ഞെടുക്കൂ',
      'map_provider_info_title': 'മാപ്പ് പ്രൊവൈഡർ (ഓട്ടോ-മാനേജ്ഡ്)',
      'map_provider_fallback': 'OpenStreetMap ഉപയോഗിക്കുന്നു (Ola Maps ലഭ്യമല്ല)',
      'map_provider_primary': 'Ola Maps ഉപയോഗിക്കുന്നു (പ്രൈമറി)',
      'privacy_policy_title': 'സ്വകാര്യതാ നയം',
      'privacy_policy_subtitle': 'ഞങ്ങളുടെ സ്വകാര്യതാ നയം കാണൂ',
      'terms_title': 'സേവന നിബന്ധനകൾ',
      'terms_subtitle': 'നിബന്ധനകളും വ്യവസ്ഥകളും കാണൂ',
      'delete_account_title': 'അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യൂ',
      'delete_account_subtitle': 'നിങ്ങളുടെ അക്കൗണ്ട് ശാശ്വതമായി ഡിലീറ്റ് ചെയ്യൂ',
      'rate_app_title': 'ആപ്പ് റേറ്റ് ചെയ്യൂ',
      'rate_app_subtitle': 'Play Store-ൽ ഞങ്ങളെ റേറ്റ് ചെയ്യൂ',
      'share_app_title': 'ആപ്പ് ഷെയർ ചെയ്യൂ',
      'share_app_subtitle': 'സുഹൃത്തുക്കളെ ക്ഷണിക്കൂ',
      'help_support_title': 'സഹായവും പിന്തുണയും',
      'help_support_subtitle': 'പ്രശ്നങ്ങൾക്ക് സഹായം നേടൂ',
      'share_link_copied_snack': 'ലിങ്ക് കോപ്പി ചെയ്തു! നിങ്ങളുടെ സുഹൃത്തുക്കളുമായി പങ്കിടൂ.',
      'could_not_open_link_snack': 'ലിങ്ക് തുറക്കാൻ കഴിഞ്ഞില്ല',
      'app_version_name': 'Allin1 സൂപ്പർ ആപ്പ്',
      'app_version_number': 'വേർഷൻ 1.0.0 (ബിൽഡ് 1)',
      'app_made_with_love': 'ஈரோட്ടിൽ ❤️ യോടെ നിർമ്മിച്ചത്',
      'delete_account_dialog_title': 'അക്കൗണ്ട് ഡിലീറ്റ് ചെയ്യണോ?',
      'delete_account_dialog_body': 'ഈ പ്രവർത്തനം പഴയപടിയാക്കാൻ കഴിയില്ല. നിങ്ങളുടെ റൈഡ് ചരിത്രം, സേവ് ചെയ്ത വിലാസങ്ങൾ, പേയ്മെന്റ് രീതികൾ എന്നിവയുൾപ്പെടെ എല്ലാ ഡാറ്റയും ശാശ്വതമായി ഡിലീറ്റ് ചെയ്യപ്പെടും.',
      'cancel_label': 'റദ്ദാക്കൂ',
      'delete_label': 'ഡിലീറ്റ്',
      'delete_account_requested_snack': 'അക്കൗണ്ട് ഡിലീഷൻ അഭ്യർത്ഥിച്ചു. സഹായത്തിന് പിന്തുണയെ ബന്ധപ്പെടൂ.',
      'select_currency_title': 'കറൻസി തിരഞ്ഞെടുക്കൂ',
      'currency_inr_name': 'ഇന്ത്യൻ രൂപ',
      'currency_usd_name': 'യുഎസ് ഡോളർ',
      'currency_eur_name': 'യൂറോ',
      'exit_app_title': 'ആപ്പ് വിടണോ?',
      'exit_app_body': 'Allin1 അടയ്ക്കണോ?',
      'press_home_to_minimize': 'മിനിമൈസ് ചെയ്യാൻ നിങ്ങളുടെ ഡിവൈസിന്റെ Home ബട്ടൺ അമർത്തുക',
      'no_label': 'വേണ്ട',
      'yes_label': 'വേണം',
      'nav_home_label': 'ഹോം',
      'nav_rewards_label': 'റിവാർഡുകൾ',
      'nav_playzone_label': 'പ്ലേ സോൺ',
      'nav_guru_label': 'ചിട്ടി AI',
      'nav_safety_label': 'സുരക്ഷ',
      'select_city_title': 'നഗരം തിരഞ്ഞെടുക്കുക',
      'use_current_location_label': 'എന്റെ നിലവിലെ ലൊക്കേഷൻ ഉപയോഗിക്കുക',
      'featured_shop_badge': '★ ഫീച്ചേർഡ് ഷോപ്പ്',
      'shop_open_label': 'തുറന്നിരിക്കുന്നു',
      'erode_fresh_name': 'ഈറോഡ് ഫ്രെഷ്',
      'erode_fresh_subtitle': '★★  · ഫ്രഷ് പലചരക്ക് സാധനങ്ങൾ',
      'promo_free_ride_title': 'നിങ്ങളുടെ ആദ്യ റൈഡ് സൗജന്യം!',
      'promo_free_ride_subtitle': 'ഈറോഡിൽ എവിടെയും ബൈക്ക് ടാക്സി ബുക്ക് ചെയ്യുക',
      'promo_book_label': 'ബുക്ക് ചെയ്യുക →',
      'promo_guru_title': '1 വർഷത്തെ ചിട്ടി AI സബ്സ്ക്രിപ്ഷൻ സൗജന്യമായി നേടൂ',
      'promo_guru_badge': 'ചിട്ടി',
      'promo_guru_subtitle': '1 വർഷത്തെ സൗജന്യ ചിട്ടി AI ഓഫർ നേടാൻ NJ TECH സന്ദർശിക്കുക.',
      'drawer_my_profile': 'എന്റെ പ്രൊഫൈൽ',
      'drawer_activity': 'പ്രവർത്തനം',
      'drawer_settings': 'ക്രമീകരണങ്ങൾ',
      'drawer_help_whatsapp': 'സഹായവും WhatsApp പിന്തുണയും',
      'drawer_check_update': 'അപ്ഡേറ്റ് പരിശോധിക്കുക',
      'drawer_download_app_title': 'ടർബോ ആപ്പ് ഡൗൺലോഡ് ചെയ്യൂ!',
      'drawer_download_app_subtitle': 'ആപ്പ് നേടി 10x വേഗത്തിൽ ഉപയോഗിക്കൂ!',
      'drawer_sign_out': 'സൈൻ ഔട്ട് / ലോഗ്ഔട്ട്',
      'app_version_footer': 'Allin1 സൂപ്പർ ആപ്പ് v1.0.0',
      'checking_updates_msg': 'അപ്ഡേറ്റുകൾ പരിശോധിക്കുന്നു...',
      'app_updating_msg': 'ദയവായി കാത്തിരിക്കൂ, ആപ്പ് അപ്ഡേറ്റ് ചെയ്യുന്നു...',
      'up_to_date_title': 'ഏറ്റവും പുതിയത്',
      'up_to_date_body': 'ആപ്പ് ഏറ്റവും പുതിയ പതിപ്പിലാണ്!\nShorebird OTA വഴി ബാക്ക്ഗ്രൗണ്ട് അപ്ഡേറ്റുകൾ സജീവമാണ്.',
      'got_it_label': 'മനസ്സിലായി',
      'already_latest_version_snack': 'നിങ്ങൾ ഇതിനകം ഏറ്റവും പുതിയ പതിപ്പിലാണ്',
      'welcome_new_version_title': 'നിങ്ങൾ തയ്യാറാണ്!',
      'welcome_new_version_body': 'Allin1-ന്റെ ഏറ്റവും പുതിയ പതിപ്പിലേക്ക് സ്വാഗതം — പുതിയ ഫീച്ചറുകളും തിരുത്തലുകളും ആസ്വദിക്കൂ.',
      'updating_app_msg': 'ആപ്പ് അപ്ഡേറ്റ് ചെയ്യുന്നു...',
      'download_failed_title': 'ഡൗൺലോഡ് ആരംഭിക്കാനായില്ല',
      'download_failed_body': 'നിങ്ങളുടെ ബ്രൗസർ നേരിട്ടുള്ള ഡൗൺലോഡ് തടഞ്ഞു. ഈ ലിങ്ക് കോപ്പി ചെയ്ത് Chrome-ൽ തുറക്കുക:',
      'copy_link_label': 'ലിങ്ക് കോപ്പി ചെയ്യുക',
      'close_label': 'അടയ്ക്കുക',
      'link_copied_snack': 'ലിങ്ക് കോപ്പി ചെയ്തു',
      'apk_sheet_title': '📲 NJ TECH ആപ്പുകൾ ഡൗൺലോഡ് ചെയ്യൂ',
      'download_customer_app_label': '🛒  കസ്റ്റമർ ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
      'download_hero_app_label': '🏍️  ഹീറോ ആപ്പ് ഡൗൺലോഡ് ചെയ്യുക',
      'dismiss_label': 'അടയ്ക്കുക',
      'reload_tooltip': 'റീലോഡ്',
      'opening_erode_fiber_msg': 'ഈറോഡ് ഫൈബർ തുറക്കുന്നു...',
      'erode_fiber_open_title': 'ഈറോഡ് ഫൈബർ തുറന്നു!',
      'erode_fiber_open_subtitle': 'സൈറ്റ് ആപ്പിനുള്ളിൽ തന്നെ ലോഡ് ചെയ്തു.',
      'back_to_dashboard_label': '← ഡാഷ്ബോർഡിലേക്ക് മടങ്ങുക',
      'could_not_open_inapp_title': 'ആപ്പിനുള്ളിൽ തുറക്കാനായില്ല',
      'check_internet_retry_subtitle': 'ഇന്റർനെറ്റ് പരിശോധിച്ച് വീണ്ടും ശ്രമിക്കുക.',
      'try_again_label': 'വീണ്ടും ശ്രമിക്കുക',
      'daily_scratch_badge': '🎰 സ്ക്രാച്ച് & വിന്',
      'scratch_reveal_hint': 'നിങ്ങളുടെ സമ്മാനം കാണാൻ സ്ക്രാച്ച് ചെയ്യൂ!',
      'scratch_reward_title': 'നിങ്ങൾ ഒരു Paytm സൗണ്ട്ബോക്സ് നേടി!',
      'scratch_reward_subtitle': 'നിങ്ങളുടെ സമ്മാനം നേടാൻ താഴെ ടാപ്പ് ചെയ്യൂ',
      'scratch_revealed_label': '🎊 വെളിപ്പെടുത്തി!',
      'scratch_keep_going_label': 'സ്ക്രാച്ച് ചെയ്തുകൊണ്ടിരിക്കൂ...',
      'call_to_claim_label': '📞 നേടാൻ വിളിക്കൂ',
      'update_badge_label': 'അപ്ഡേറ്റ്',
      'category_taxi_slide': '🚕 ടാക്സിയും ഗതാഗതവും',
      'category_food_slide': '🍔 ഫുഡ് ഡെലിവറി',
      'category_grocery_slide': '🛒 പലചരക്ക്',
      'category_services_slide': '🔧 സേവനങ്ങൾ',
      'downloading_update_snack': 'അപ്ഡേറ്റ് ഡൗൺലോഡ് ചെയ്യുന്നു...',
      'promo_firstride_title': 'ആദ്യ റൈഡ് സൗജന്യം 🛵',
      'promo_firstride_subtitle': 'പുതിയ ഉപയോക്താവാണോ? നിങ്ങളുടെ ആദ്യ ടാക്സി റൈഡ് ഞങ്ങളുടെ വക!',
      'promo_book_now_label': 'ഇപ്പോൾ ബുക്ക് ചെയ്യുക',
      'promo_new_users_label': 'പുതിയ ഉപയോക്താക്കൾ',
      'promo_claimed_label': 'നേടി ✓',
      'tour_welcome_title': 'Allin1-ലേക്ക് സ്വാഗതം! 👋',
      'tour_welcome_desc': 'ഈറോഡിന് വേണ്ടതെല്ലാം ഒറ്റ ആപ്പിൽ — ബൈക്ക് ടാക്സി, ഫുഡ് ഡെലിവറി, പലചരക്ക്, ടെക് സ്റ്റോർ എന്നിവയും അതിലേറെയും. അടിസ്ഥാനങ്ങളുടെ വേഗത്തിലുള്ള ടൂർ വേണോ?',
      'tour_home_desc': 'ടാക്സി ബുക്ക് ചെയ്യുക, ഭക്ഷണം/പലചരക്ക് ഓർഡർ ചെയ്യുക, അല്ലെങ്കിൽ പ്രത്യേക സേവനം ചോദിക്കുക — എല്ലാം ഇവിടെ നിന്ന് തന്നെ.',
      'tour_rewards_desc': 'സൗജന്യ Paytm ബോക്സ് അല്ലെങ്കിൽ ചിട്ടി AI സബ്സ്ക്രിപ്ഷൻ പോലുള്ള യഥാർത്ഥ റിവാർഡുകൾ അൺലോക്ക് ചെയ്യാൻ വേഗത്തിലുള്ള ക്വിസുകൾക്ക് ഉത്തരം നൽകുക.',
      'tour_playzone_desc': 'നിങ്ങളുടെ റൈഡിനോ ഓർഡറിനോ കാത്തിരിക്കുമ്പോൾ 2048, Whack-a-Mole പോലുള്ള വേഗത്തിലുള്ള ഗെയിമുകൾ കളിക്കുക.',
      'tour_guru_desc': 'നിങ്ങളുടെ AI അസിസ്റ്റന്റ് — ബുക്കിംഗ്, ട്രാക്കിംഗ് അല്ലെങ്കിൽ ആപ്പിനെക്കുറിച്ച് എന്തും ചോദിക്കൂ.',
      'tour_safety_desc': 'നിങ്ങൾക്ക് ഏറ്റവും ആവശ്യമുള്ളപ്പോൾ യഥാർത്ഥ സുരക്ഷയ്ക്കായി വൺ-ടാപ്പ് SOS അടിയന്തര സഹായം.',
      'eseva_xerox': 'സെറോക്സ് & കളർ പ്രിന്റൗട്ട്',
      'eseva_voter_id': 'വോട്ടർ ഐഡി',
      'eseva_pan': 'പാൻ കാർഡ്',
      'eseva_aadhaar': 'ആധാർ കാർഡ് അപ്ഡേറ്റ്',
      'eseva_rental': 'റെന്റൽ എഗ്രിമെന്റ് & ജോബ് ടൈപ്പിംഗ്',
      'eseva_employment': 'തൊഴിൽ രജിസ്ട്രേഷൻ',
      'eseva_ration': 'റേഷൻ കാർഡ്',
      'eseva_birth_death': 'ജനന & മരണ സർട്ടിഫിക്കറ്റ്',
      'eseva_fssai_msme': 'FSSAI / MSME / UDYAM',
      'eseva_certificate': 'വരുമാന, നേറ്റിവിറ്റി & കമ്മ്യൂണിറ്റി സർട്ടിഫിക്കറ്റ്',
      'eseva_ayushman': 'ആയുഷ്മാൻ കാർഡ്',
      'eseva_eshram': 'ഇ-ശ്രം കാർഡ്',
      'eseva_laptop': 'ലാപ്ടോപ്പ് & കമ്പ്യൂട്ടർ സെയിൽസ്/സർവീസ്',
      'eseva_photo_print': 'ഫോട്ടോ പ്രിന്റ്',
      'eseva_pvc': 'പിവിസി പ്ലാസ്റ്റിക് കാർഡ് പ്രിന്റ്',
    },
  };

  String _languageCode;

  String get languageCode => _languageCode;

  String get languageLabel {
    switch (_languageCode) {
      case 'ta':
        return 'தமிழ்';
      case 'tg':
        return 'Tanglish';
      case 'hi':
        return 'हिन्दी';
      case 'ml':
        return 'മലയാളം';
      default:
        return 'English';
    }
  }

  String t(String key) {
    return _translations[_languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  Future<void> setLanguage(String code) async {
    if (!_translations.containsKey(code) || code == _languageCode) {
      return;
    }

    _languageCode = code;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, _languageCode);
  }

  Future<void> _loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_prefsKey);
    if (savedLanguage == null ||
        !_translations.containsKey(savedLanguage) ||
        savedLanguage == _languageCode) {
      return;
    }

    _languageCode = savedLanguage;
    notifyListeners();
  }
}
