import 'dart:async';

import 'package:flutter/foundation.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  LocalizationService({String initialLanguage = 'en'})
      : _languageCode = initialLanguage {
    unawaited(_loadSavedLanguage());
  }

  static const String _prefsKey = 'customer_language_code';

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'my allin1',
      'greeting': 'Hello',
      'what_need_today': 'What do you need today?',
      'bike_taxi_title': 'Bike Taxi',
      'bike_taxi_subtitle': 'Fast rides in Erode',
      'food_delivery_title': 'Food Delivery',
      'food_delivery_subtitle': '16th Road specials',
      'grocery_title': 'Grocery',
      'grocery_subtitle': 'Fresh and fast',
      'tech_store_title': 'Tech Store',
      'tech_store_subtitle': 'NJ TECH gadgets',
      'custom_order_title': 'Custom Order',
      'custom_order_subtitle': 'Ask for special service',
      'broadband_title': 'Broadband / WiFi',
      'broadband_subtitle': 'Manage your internet service',
      'mobile_puncture_title': 'Mobile Puncture',
      'mobile_puncture_subtitle': 'Fast puncture repair',
      'pharmacy_title': 'Pharmacy',
      'pharmacy_subtitle': 'Medicines delivered',
      'book_puncture': 'Book for Puncture?',
      'call_now': 'Call Now',
      'later': 'Later',
      'service_coming_soon': 'Launching soon!',
      'language_label': 'Language',
      'home_label': 'Home',
      'chat_label': 'Live Rates',
      'rides_label': 'Play Zone',
      'account_label': 'Account',
      'my_rides_label': 'My Rides',
      'live_rates_label': 'Live Rates',
      'play_zone_label': 'Play Zone',
      'live_label': 'Live',
      'erode_label': 'Erode, Tamil Nadu',
      'live_rates_title': 'Live Rates',
      'live_rates_subtitle':
          'Gold, silver and fuel prices in one quick glance for Erode.',
      'today_price_label': "Today's Price",
      'play_zone_title': 'Play Zone',
      'play_zone_subtitle':
          'Solve the 3x3 NJ TECH puzzle and beat your best time.',
      'sliding_puzzle_title': 'Sliding Puzzle Game',
      'moves_label': 'Moves',
      'time_label': 'Time',
      'reset_label': 'Reset',
      'play_again_label': 'Play Again',
      'puzzle_instruction':
          'Align the NJ TECH and Erode pattern pieces perfectly.',
      'solved_title': 'You solved it!',
      'solved_message_intro': 'Brilliant moves!',
      'bike_label': 'Bike',
      'auto_label': 'Auto',
      'cab_label': 'Cab',
      'parcel_label': 'Parcel',
      'mini_truck_label': 'Mini Truck',
      'lorry_label': 'Lorry',
      'emergency_manpower_label': 'SOS',
      'where_to_go_hint': 'Where do you want to go?',
      'choose_vehicle_label': 'Choose Vehicle',
      'distance_label': 'Distance',
      'eta_label': 'ETA',
      'choose_destination_title': 'Choose destination',
      'update_pickup_title': 'Update pickup',
      'drag_map_hint':
          'Drag the map or type 3 letters to find a place in Erode.',
      'pickup_location_label': 'Pickup location',
      'drop_destination_label': 'Drop destination',
      'drop_pin_destination_title': 'Drop pin for destination',
      'drop_pin_pickup_title': 'Drop pin for pickup',
      'finding_street_label': 'Finding the exact street address...',
      'move_map_to_select_label': 'Move the map to select',
      'use_as_destination_label': 'Use as Destination',
      'use_as_pickup_label': 'Use as Pickup',
      'pay_via_soundbox': 'Pay your bill via Paytm box',
      'scan_soundbox_qr': 'Scan the physical soundbox QR and confirm once the amount is paid.',
      'awaiting_hero_payment': 'Waiting for Hero Confirmation...',
      'scan_and_wait_hero': 'Please scan the Paytm Soundbox and wait while the Hero confirms your bill.',
      'open_upi_scan_soundbox': 'Open Paytm through the UPI chooser, scan the Hero Paytm Soundbox, and complete the exact bill amount.',
      // ── Home screen "mega card" titles/subtitles (Nizam's whole-app
      // language retrofit, phase 1: dashboard_screen.dart) ──
      'hero_booking_mega_title': 'Hero Booking',
      'hero_booking_mega_subtitle': 'Hire a Hero for any tasks & deliveries',
      'taxi_mega_title': 'Taxi & Transportation',
      'taxi_mega_subtitle': 'Bike, Auto, Cab, Parcel & Rent',
      'food_mega_subtitle': 'Order from ANY shop in Erode!',
      'grocery_mega_title': 'Grocery Order',
      'grocery_mega_subtitle': 'Type your list or snap a photo',
      'electronics_mega_title': 'Electronic Services',
      'electronics_mega_subtitle': 'Mobile, Laptop, PC, CCTV, TV & AC',
      'carservice_mega_title': 'Car Service & Wash',
      'carservice_mega_subtitle': 'Water Wash, Repairs & Old Spares',
      'construction_mega_title': 'Constructions & Building',
      'construction_mega_subtitle': 'Usha Constructions, Contracts & Plans',
      'printing_mega_title': 'Designing & Printing',
      'printing_mega_subtitle': 'Visiting Cards, Flex, Bill Books & Notices',
      'otherservices_mega_title': 'Other Services',
      'otherservices_mega_subtitle': 'Broadband, Mobile Puncture & More',
      'other_internet_label': 'Internet',
      'other_puncture_label': 'Puncture',
      'other_cleaning_label': 'Cleaning',
      'other_electrician_label': 'Electrician',
      'greeting_hi': 'Hi',
      // ── Food Hub screen ──
      'food_hub_prompt': 'What would you like to order?',
      'food_hub_custom_subtitle': 'Order from any shop in Erode',
      'food_hub_shops_heading': 'Order from your favourite shops',
      'food_hub_shops_subheading': 'Order & pay on their site — our hero picks it up & delivers it to you.',
      // ── Settings screen (Nizam's i18n phase 1: settings_screen.dart) ──
      'settings_title': 'Settings',
      'notifications_section': 'Notifications',
      'push_notifications_title': 'Push Notifications',
      'push_notifications_subtitle': 'Receive push notifications',
      'ride_alerts_title': 'Ride Alerts',
      'ride_alerts_subtitle': 'Get updates about your rides',
      'promotional_alerts_title': 'Promotional Alerts',
      'promotional_alerts_subtitle': 'Offers and deals',
      'preferences_section': 'Preferences',
      'location_services_title': 'Location Services',
      'location_services_subtitle': 'Allow app to access location',
      'biometric_login_title': 'Biometric Login',
      'biometric_login_subtitle': 'Use fingerprint for quick login',
      'dark_mode_title': 'Dark Mode',
      'dark_mode_subtitle': 'Dark theme is currently active',
      'theme_title': 'Theme',
      'theme_subtitle': 'Pick your favourite look',
      'map_provider_section': 'Map Provider',
      'language_region_section': 'Language & Region',
      'privacy_security_section': 'Privacy & Security',
      'about_section': 'About',
      'language_picker_title': 'Language / Mozhi',
      'language_picker_subtitle': 'Pick how you want app text to look',
    },
    'ta': {
      'app_title': 'my allin1',
      'greeting': 'வணக்கம்',
      'what_need_today': 'இன்று என்ன வேண்டும்?',
      'bike_taxi_title': 'பைக் டாக்ஸி',
      'bike_taxi_subtitle': 'ஈரோட்டில் வேகமான பயணம்',
      'food_delivery_title': 'உணவு டெலிவரி',
      'food_delivery_subtitle': '16வது ரோடு சிறப்புகள்',
      'grocery_title': 'மளிகை',
      'grocery_subtitle': 'புதியதும் வேகமும்',
      'tech_store_title': 'டெக் ஸ்டோர்',
      'tech_store_subtitle': 'NJ TECH சாதனங்கள்',
      'custom_order_title': 'கஸ்டம் ஆர்டர்',
      'custom_order_subtitle': 'சிறப்பு சேவையை கேளுங்கள்',
      'broadband_title': 'இணைய சேவை',
      'broadband_subtitle': 'உங்கள் இணைய சேவையை நிர்வகிக்கவும்',
      'mobile_puncture_title': 'மொபைல் பஞ்சர்',
      'mobile_puncture_subtitle': 'விரைவு பஞ்சர் பழுது பார்க்க',
      'pharmacy_title': 'மருந்தகம்',
      'pharmacy_subtitle': 'மருந்துகள் டெலிவரி',
      'book_puncture': 'பஞ்சருக்கு புக் செய்யவா?',
      'call_now': 'இப்போதே அழைக்கவும்',
      'later': 'பிறகு',
      'service_coming_soon': 'விரைவில் வருகிறது!',
      'language_label': 'மொழி',
      'home_label': 'முகப்பு',
      'chat_label': 'நேரலை விலைகள்',
      'rides_label': 'ப்ளே சோன்',
      'account_label': 'கணக்கு',
      'my_rides_label': 'என் பயணங்கள்',
      'live_rates_label': 'நேரலை விலைகள்',
      'play_zone_label': 'ப்ளே சோன்',
      'live_label': 'நேரலை',
      'erode_label': 'ஈரோடு, தமிழ்நாடு',
      'live_rates_title': 'நேரலை விலைகள்',
      'live_rates_subtitle':
          'ஈரோட்டிற்கான தங்கம், வெள்ளி, எரிபொருள் விலைகள் ஒரே பார்வையில்.',
      'today_price_label': 'இன்றைய விலை',
      'play_zone_title': 'ப்ளே சோன்',
      'play_zone_subtitle':
          'NJ TECH 3x3 புதிரை தீர்த்து உங்கள் சிறந்த நேரத்தை வெல்லுங்கள்.',
      'sliding_puzzle_title': 'சறுக்கும் புதிர் விளையாட்டு',
      'moves_label': 'நகர்வுகள்',
      'time_label': 'நேரம்',
      'reset_label': 'மீட்டமை',
      'play_again_label': 'மீண்டும் விளையாடு',
      'puzzle_instruction':
          'NJ TECH மற்றும் ஈரோடு வடிவங்களை சரியாக ஒழுங்குபடுத்து.',
      'solved_title': 'நீங்கள் தீர்த்துவிட்டீர்கள்!',
      'solved_message_intro': 'சிறப்பான நகர்வுகள்!',
      'bike_label': 'பைக்',
      'auto_label': 'ஆட்டோ',
      'cab_label': 'கார்',
      'parcel_label': 'பார்சல்',
      'where_to_go_hint': 'எங்கே செல்ல வேண்டும்?',
      'choose_vehicle_label': 'வாகனத்தை தேர்வு செய்',
      'distance_label': 'தூரம்',
      'eta_label': 'நேரம்',
      'choose_destination_title': 'இறங்கும் இடத்தை தேர்வு செய்',
      'update_pickup_title': 'பிக்கப் இடத்தை மாற்று',
      'drag_map_hint':
          'ஈரோட்டில் இடம் காண மேப்பை இழுக்கவும் அல்லது 3 எழுத்துகள் தட்டச்சு செய்யவும்.',
      'pickup_location_label': 'பிக்கப் இடம்',
      'drop_destination_label': 'இறங்கும் இடம்',
      'drop_pin_destination_title': 'இறங்கும் இடத்திற்கு பின் இடு',
      'drop_pin_pickup_title': 'பிக்கப் இடத்திற்கு பின் இடு',
      'finding_street_label': 'சரியான தெரு முகவரியை கண்டுபிடிக்கிறது...',
      'move_map_to_select_label': 'தேர்வு செய்ய மேப்பை நகர்த்து',
      'use_as_destination_label': 'இறங்கும் இடமாக பயன்படுத்து',
      'use_as_pickup_label': 'பிக்கப் இடமாக பயன்படுத்து',
      'pay_via_soundbox': 'Paytm சவுண்ட்பாக்ஸ் மூலம் பில் செலுத்தவும்',
      'scan_soundbox_qr': 'சவுண்ட்பாக்ஸ் QR ஐ ஸ்கேன் செய்து, பணம் செலுத்தியதும் உறுதிசெய்யவும்.',
      'awaiting_hero_payment': 'ஹீரோ உறுதிப்படுத்தலுக்காக காத்திருக்கிறது...',
      'scan_and_wait_hero': 'Paytm சவுண்ட்பாக்ஸை ஸ்கேன் செய்து, ஹீரோ உங்கள் பில்லை உறுதிப்படுத்தும் வரை காத்திருக்கவும்.',
      'open_upi_scan_soundbox': 'UPI தேர்வு மூலம் Paytm ஐ திறந்து, ஹீரோவின் Paytm சவுண்ட்பாக்ஸை ஸ்கேன் செய்து, சரியான பில் தொகையை செலுத்தவும்.',
      'hero_booking_mega_title': 'ஹீரோ புக்கிங்',
      'hero_booking_mega_subtitle': 'எந்த வேலைக்கும் டெலிவரிக்கும் ஹீரோவை அமர்த்துங்கள்',
      'taxi_mega_title': 'டாக்ஸி & போக்குவரத்து',
      'taxi_mega_subtitle': 'பைக், ஆட்டோ, கார், பார்சல் & வாடகை',
      'food_mega_subtitle': 'ஈரோட்டில் எந்த கடையிலிருந்தும் ஆர்டர் செய்யுங்கள்!',
      'grocery_mega_title': 'மளிகை ஆர்டர்',
      'grocery_mega_subtitle': 'உங்கள் லிஸ்ட்டை டைப் செய்யுங்கள் அல்லது புகைப்படம் எடுங்கள்',
      'electronics_mega_title': 'எலக்ட்ரானிக் சேவைகள்',
      'electronics_mega_subtitle': 'மொபைல், லேப்டாப், பிசி, சிசிடிவி, டிவி & ஏசி',
      'carservice_mega_title': 'கார் சர்வீஸ் & வாஷ்',
      'carservice_mega_subtitle': 'வாட்டர் வாஷ், ரிப்பேர் & பழைய பாகங்கள்',
      'construction_mega_title': 'கட்டுமானம் & பில்டிங்',
      'construction_mega_subtitle': 'உஷா கன்ஸ்ட்ரக்சன்ஸ், ஒப்பந்தங்கள் & திட்டங்கள்',
      'printing_mega_title': 'டிசைனிங் & பிரிண்டிங்',
      'printing_mega_subtitle': 'விசிட்டிங் கார்டு, ஃப்ளெக்ஸ், பில் புக்ஸ் & நோட்டீஸ்',
      'otherservices_mega_title': 'மற்ற சேவைகள்',
      'otherservices_mega_subtitle': 'ப்ராட்பேண்ட், மொபைல் பஞ்சர் & மேலும்',
      'other_internet_label': 'இணையம்',
      'other_puncture_label': 'பஞ்சர்',
      'other_cleaning_label': 'சுத்தம்',
      'other_electrician_label': 'எலக்ட்ரீஷியன்',
      'greeting_hi': 'ஹாய்',
      'food_hub_prompt': 'என்ன ஆர்டர் செய்ய விரும்புகிறீர்கள்?',
      'food_hub_custom_subtitle': 'ஈரோட்டில் எந்த கடையிலிருந்தும் ஆர்டர் செய்யுங்கள்',
      'food_hub_shops_heading': 'உங்களுக்கு பிடித்த கடைகளிலிருந்து ஆர்டர் செய்யுங்கள்',
      'food_hub_shops_subheading': 'அவர்களின் தளத்தில் ஆர்டர் செய்து பணம் செலுத்துங்கள் — எங்கள் ஹீரோ அதை எடுத்து உங்களிடம் கொண்டு வருவார்.',
      'settings_title': 'அமைப்புகள்',
      'notifications_section': 'அறிவிப்புகள்',
      'push_notifications_title': 'புஷ் அறிவிப்புகள்',
      'push_notifications_subtitle': 'புஷ் அறிவிப்புகளைப் பெறவும்',
      'ride_alerts_title': 'பயண அறிவிப்புகள்',
      'ride_alerts_subtitle': 'உங்கள் பயணங்கள் பற்றிய அறிவிப்புகள்',
      'promotional_alerts_title': 'விளம்பர அறிவிப்புகள்',
      'promotional_alerts_subtitle': 'சலுகைகள் & ஆஃபர்கள்',
      'preferences_section': 'விருப்பங்கள்',
      'location_services_title': 'இருப்பிட சேவைகள்',
      'location_services_subtitle': 'இருப்பிடத்தை அணுக அனுமதிக்கவும்',
      'biometric_login_title': 'பயோமெட்ரிக் லாகின்',
      'biometric_login_subtitle': 'விரைவு லாகினுக்கு கைரேகையை பயன்படுத்தவும்',
      'dark_mode_title': 'டார்க் மோட்',
      'dark_mode_subtitle': 'டார்க் தீம் தற்போது இயக்கத்தில் உள்ளது',
      'theme_title': 'தீம்',
      'theme_subtitle': 'உங்களுக்கு பிடித்த தோற்றத்தை தேர்வு செய்யவும்',
      'map_provider_section': 'மேப் வழங்குநர்',
      'language_region_section': 'மொழி & பகுதி',
      'privacy_security_section': 'தனியுரிமை & பாதுகாப்பு',
      'about_section': 'பற்றி',
      'language_picker_title': 'மொழி / Mozhi',
      'language_picker_subtitle': 'ஆப் டெக்ஸ்ட் எப்படி இருக்க வேண்டும் என தேர்வு செய்யவும்',
    },
    'tg': {
      'app_title': 'my allin1',
      'greeting': 'Vanakkam',
      'what_need_today': 'Innaiku enna venum?',
      'bike_taxi_title': 'Bike Taxi',
      'bike_taxi_subtitle': 'Erode la fast ride',
      'food_delivery_title': 'Food Delivery',
      'food_delivery_subtitle': '16th road special sapadu',
      'grocery_title': 'Grocery',
      'grocery_subtitle': 'Fresh ahum fast ahum',
      'tech_store_title': 'Tech Store',
      'tech_store_subtitle': 'NJ TECH gadgets',
      'custom_order_title': 'Custom Order',
      'custom_order_subtitle': 'Special service kekkalam',
      'broadband_title': 'Internet Bill',
      'broadband_subtitle': 'Internet service manage pannu',
      'mobile_puncture_title': 'Mobile Puncture',
      'mobile_puncture_subtitle': 'Vandi puncture repair on call',
      'pharmacy_title': 'Pharmacy',
      'pharmacy_subtitle': 'Medicine delivery',
      'book_puncture': 'Puncture-ku book pannu?',
      'call_now': 'Call Now',
      'later': 'Apram',
      'service_coming_soon': 'Seekiram varudhu!',
      'language_label': 'Language',
      'home_label': 'Home',
      'chat_label': 'Live Rates',
      'rides_label': 'Play Zone',
      'account_label': 'Account',
      'my_rides_label': 'En rides',
      'live_rates_label': 'Live Rates',
      'play_zone_label': 'Play Zone',
      'live_label': 'Live',
      'erode_label': 'Erode, Tamil Nadu',
      'live_rates_title': 'Live Rates',
      'live_rates_subtitle':
          'Gold, silver, petrol rate ellam ore glance la paakalam.',
      'today_price_label': 'Innaiku rate',
      'play_zone_title': 'Play Zone',
      'play_zone_subtitle':
          'NJ TECH 3x3 puzzle solve panni unga best time beat pannunga.',
      'sliding_puzzle_title': 'Sarukkum Puthir Vilayattu',
      'moves_label': 'Moves',
      'time_label': 'Time',
      'reset_label': 'Reset',
      'play_again_label': 'Play Again',
      'puzzle_instruction':
          'NJ TECH um Erode pattern pieces um straight ah align pannunga.',
      'solved_title': 'Neenga theerthuttinga!',
      'solved_message_intro': 'Semma moves!',
      'bike_label': 'Bike',
      'auto_label': 'Auto',
      'cab_label': 'Cab',
      'parcel_label': 'Parcel',
      'mini_truck_label': 'Mini Truck',
      'lorry_label': 'Lorry',
      'emergency_manpower_label': 'SOS',
      'where_to_go_hint': 'Enga poganum?',
      'choose_vehicle_label': 'Vehicle choose pannu',
      'distance_label': 'Distance',
      'eta_label': 'ETA',
      'choose_destination_title': 'Destination choose pannu',
      'update_pickup_title': 'Pickup update pannu',
      'drag_map_hint':
          'Erode la place find panna map drag pannunga illa 3 letters type pannunga.',
      'pickup_location_label': 'Pickup location',
      'drop_destination_label': 'Drop destination',
      'drop_pin_destination_title': 'Destination-ku pin podu',
      'drop_pin_pickup_title': 'Pickup-ku pin podu',
      'finding_street_label': 'Exact street address theduthu irukom...',
      'move_map_to_select_label': 'Select panna map move pannunga',
      'use_as_destination_label': 'Destination ah use pannu',
      'use_as_pickup_label': 'Pickup ah use pannu',
      'pay_via_soundbox': 'Paytm soundbox la bill kattru',
      'scan_soundbox_qr': 'Soundbox QR scan pannitu, amount pay pannitu confirm pannu.',
      'awaiting_hero_payment': 'Hero confirmation ku waiting...',
      'scan_and_wait_hero': 'Paytm Soundbox scan pannitu, Hero unga bill confirm panna vara wait pannu.',
      'open_upi_scan_soundbox': 'UPI la Paytm open pannu, Hero Soundbox scan pannu, exact bill amount pay pannu.',
      'hero_booking_mega_title': 'Hero Booking',
      'hero_booking_mega_subtitle': 'Yenna vela irunthalum Hero-a book pannunga',
      'taxi_mega_title': 'Taxi & Transport',
      'taxi_mega_subtitle': 'Bike, Auto, Cab, Parcel & Rent',
      'food_mega_subtitle': 'Erode la ethachum shop-la irunthu order pannunga!',
      'grocery_mega_title': 'Grocery Order',
      'grocery_mega_subtitle': 'Unga list type pannunga illa photo eduthu anuppunga',
      'electronics_mega_title': 'Electronic Services',
      'electronics_mega_subtitle': 'Mobile, Laptop, PC, CCTV, TV & AC',
      'carservice_mega_title': 'Car Service & Wash',
      'carservice_mega_subtitle': 'Water wash, repair & old spares',
      'construction_mega_title': 'Construction & Building',
      'construction_mega_subtitle': 'Usha Constructions, contracts & plans',
      'printing_mega_title': 'Designing & Printing',
      'printing_mega_subtitle': 'Visiting card, flex, bill book & notice',
      'otherservices_mega_title': 'Other Services',
      'otherservices_mega_subtitle': 'Broadband, mobile puncture & more',
      'other_internet_label': 'Internet',
      'other_puncture_label': 'Puncture',
      'other_cleaning_label': 'Cleaning',
      'other_electrician_label': 'Electrician',
      'greeting_hi': 'Hi',
      'food_hub_prompt': 'Enna order pannanum?',
      'food_hub_custom_subtitle': 'Erode la ethachum shop-la irunthu order pannunga',
      'food_hub_shops_heading': 'Unga favourite shops-la irunthu order pannunga',
      'food_hub_shops_subheading': 'Avanga site-la order pannunga pay pannunga — namma hero adha eduthu unga kitta kondu varuvaru.',
      'settings_title': 'Settings',
      'notifications_section': 'Notifications',
      'push_notifications_title': 'Push Notifications',
      'push_notifications_subtitle': 'Push notifications receive pannunga',
      'ride_alerts_title': 'Ride Alerts',
      'ride_alerts_subtitle': 'Unga rides pathi updates',
      'promotional_alerts_title': 'Promotional Alerts',
      'promotional_alerts_subtitle': 'Offers & deals',
      'preferences_section': 'Preferences',
      'location_services_title': 'Location Services',
      'location_services_subtitle': 'App location access panna anumathi kudunga',
      'biometric_login_title': 'Biometric Login',
      'biometric_login_subtitle': 'Quick login-ku fingerprint use pannunga',
      'dark_mode_title': 'Dark Mode',
      'dark_mode_subtitle': 'Dark theme ippo active ah irukku',
      'theme_title': 'Theme',
      'theme_subtitle': 'Unga favourite look ah select pannunga',
      'map_provider_section': 'Map Provider',
      'language_region_section': 'Language & Region',
      'privacy_security_section': 'Privacy & Security',
      'about_section': 'About',
      'language_picker_title': 'Language / Mozhi',
      'language_picker_subtitle': 'App text style select pannunga',
    },
    // FIX (Nizam's language request): added Hindi as the 4th supported
    // language, keyed off the SAME keys as en/ta/tg so every existing
    // t('key') call site automatically gains Hindi support with zero
    // other code changes.
    'hi': {
      'app_title': 'my allin1',
      'greeting': 'नमस्ते',
      'what_need_today': 'आज आपको क्या चाहिए?',
      'bike_taxi_title': 'बाइक टैक्सी',
      'bike_taxi_subtitle': 'ईरोड में तेज़ सवारी',
      'food_delivery_title': 'फ़ूड डिलीवरी',
      'food_delivery_subtitle': '16वीं रोड की खासियतें',
      'grocery_title': 'किराना',
      'grocery_subtitle': 'ताज़ा और तेज़',
      'tech_store_title': 'टेक स्टोर',
      'tech_store_subtitle': 'NJ TECH गैजेट्स',
      'custom_order_title': 'कस्टम ऑर्डर',
      'custom_order_subtitle': 'खास सेवा के लिए पूछें',
      'broadband_title': 'ब्रॉडबैंड / वाईफाई',
      'broadband_subtitle': 'अपनी इंटरनेट सेवा प्रबंधित करें',
      'mobile_puncture_title': 'मोबाइल पंक्चर',
      'mobile_puncture_subtitle': 'तुरंत पंक्चर मरम्मत',
      'pharmacy_title': 'फार्मेसी',
      'pharmacy_subtitle': 'दवाइयाँ घर पहुंचाई जाएंगी',
      'book_puncture': 'पंक्चर के लिए बुक करें?',
      'call_now': 'अभी कॉल करें',
      'later': 'बाद में',
      'service_coming_soon': 'जल्द ही आ रहा है!',
      'language_label': 'भाषा',
      'home_label': 'होम',
      'chat_label': 'लाइव रेट्स',
      'rides_label': 'प्ले ज़ोन',
      'account_label': 'खाता',
      'my_rides_label': 'मेरी सवारियाँ',
      'live_rates_label': 'लाइव रेट्स',
      'play_zone_label': 'प्ले ज़ोन',
      'live_label': 'लाइव',
      'erode_label': 'ईरोड, तमिलनाडु',
      'live_rates_title': 'लाइव रेट्स',
      'live_rates_subtitle':
          'ईरोड के लिए सोना, चांदी और पेट्रोल की कीमतें एक ही नज़र में।',
      'today_price_label': 'आज की कीमत',
      'play_zone_title': 'प्ले ज़ोन',
      'play_zone_subtitle':
          'NJ TECH 3x3 पहेली हल करें और अपना सबसे अच्छा समय हराएं।',
      'sliding_puzzle_title': 'स्लाइडिंग पज़ल गेम',
      'moves_label': 'चालें',
      'time_label': 'समय',
      'reset_label': 'रीसेट',
      'play_again_label': 'फिर से खेलें',
      'puzzle_instruction':
          'NJ TECH और ईरोड के पैटर्न टुकड़ों को सही तरीके से मिलाएं।',
      'solved_title': 'आपने हल कर लिया!',
      'solved_message_intro': 'शानदार चालें!',
      'bike_label': 'बाइक',
      'auto_label': 'ऑटो',
      'cab_label': 'कैब',
      'parcel_label': 'पार्सल',
      'mini_truck_label': 'मिनी ट्रक',
      'lorry_label': 'लॉरी',
      'emergency_manpower_label': 'एसओएस',
      'where_to_go_hint': 'आप कहाँ जाना चाहते हैं?',
      'choose_vehicle_label': 'वाहन चुनें',
      'distance_label': 'दूरी',
      'eta_label': 'ईटीए',
      'choose_destination_title': 'गंतव्य चुनें',
      'update_pickup_title': 'पिकअप अपडेट करें',
      'drag_map_hint':
          'ईरोड में जगह खोजने के लिए मैप खींचें या 3 अक्षर टाइप करें।',
      'pickup_location_label': 'पिकअप स्थान',
      'drop_destination_label': 'ड्रॉप गंतव्य',
      'drop_pin_destination_title': 'गंतव्य के लिए पिन लगाएं',
      'drop_pin_pickup_title': 'पिकअप के लिए पिन लगाएं',
      'finding_street_label': 'सही सड़क का पता खोजा जा रहा है...',
      'move_map_to_select_label': 'चुनने के लिए मैप को हिलाएं',
      'use_as_destination_label': 'गंतव्य के रूप में उपयोग करें',
      'use_as_pickup_label': 'पिकअप के रूप में उपयोग करें',
      'pay_via_soundbox': 'Paytm साउंडबॉक्स से बिल भरें',
      'scan_soundbox_qr': 'फिजिकल साउंडबॉक्स QR स्कैन करें और भुगतान होने पर पुष्टि करें।',
      'awaiting_hero_payment': 'हीरो की पुष्टि का इंतज़ार है...',
      'scan_and_wait_hero': 'कृपया Paytm साउंडबॉक्स स्कैन करें और हीरो द्वारा आपके बिल की पुष्टि होने तक प्रतीक्षा करें।',
      'open_upi_scan_soundbox': 'UPI चूज़र से Paytm खोलें, हीरो का Paytm साउंडबॉक्स स्कैन करें, और सही बिल राशि पूरी करें।',
      'hero_booking_mega_title': 'हीरो बुकिंग',
      'hero_booking_mega_subtitle': 'किसी भी काम या डिलीवरी के लिए हीरो बुक करें',
      'taxi_mega_title': 'टैक्सी और परिवहन',
      'taxi_mega_subtitle': 'बाइक, ऑटो, कैब, पार्सल और किराया',
      'food_mega_subtitle': 'ईरोड की किसी भी दुकान से ऑर्डर करें!',
      'grocery_mega_title': 'किराना ऑर्डर',
      'grocery_mega_subtitle': 'अपनी लिस्ट टाइप करें या फोटो खींचें',
      'electronics_mega_title': 'इलेक्ट्रॉनिक सेवाएं',
      'electronics_mega_subtitle': 'मोबाइल, लैपटॉप, पीसी, सीसीटीवी, टीवी और एसी',
      'carservice_mega_title': 'कार सर्विस और वॉश',
      'carservice_mega_subtitle': 'वॉटर वॉश, मरम्मत और पुराने पुर्जे',
      'construction_mega_title': 'निर्माण और बिल्डिंग',
      'construction_mega_subtitle': 'उषा कंस्ट्रक्शन्स, अनुबंध और योजनाएं',
      'printing_mega_title': 'डिज़ाइनिंग और प्रिंटिंग',
      'printing_mega_subtitle': 'विज़िटिंग कार्ड, फ्लेक्स, बिल बुक और नोटिस',
      'otherservices_mega_title': 'अन्य सेवाएं',
      'otherservices_mega_subtitle': 'ब्रॉडबैंड, मोबाइल पंक्चर और अधिक',
      'other_internet_label': 'इंटरनेट',
      'other_puncture_label': 'पंक्चर',
      'other_cleaning_label': 'सफाई',
      'other_electrician_label': 'इलेक्ट्रीशियन',
      'greeting_hi': 'नमस्ते',
      'food_hub_prompt': 'आप क्या ऑर्डर करना चाहेंगे?',
      'food_hub_custom_subtitle': 'ईरोड की किसी भी दुकान से ऑर्डर करें',
      'food_hub_shops_heading': 'अपनी पसंदीदा दुकानों से ऑर्डर करें',
      'food_hub_shops_subheading': 'उनकी साइट पर ऑर्डर करें और भुगतान करें — हमारा हीरो उसे लेकर आपके पास पहुंचाएगा।',
      'settings_title': 'सेटिंग्स',
      'notifications_section': 'सूचनाएं',
      'push_notifications_title': 'पुश नोटिफिकेशन',
      'push_notifications_subtitle': 'पुश नोटिफिकेशन प्राप्त करें',
      'ride_alerts_title': 'सवारी अलर्ट',
      'ride_alerts_subtitle': 'अपनी सवारियों के बारे में अपडेट पाएं',
      'promotional_alerts_title': 'प्रचार अलर्ट',
      'promotional_alerts_subtitle': 'ऑफ़र और डील्स',
      'preferences_section': 'प्राथमिकताएं',
      'location_services_title': 'लोकेशन सेवाएं',
      'location_services_subtitle': 'ऐप को लोकेशन एक्सेस करने दें',
      'biometric_login_title': 'बायोमेट्रिक लॉगिन',
      'biometric_login_subtitle': 'तेज़ लॉगिन के लिए फिंगरप्रिंट का उपयोग करें',
      'dark_mode_title': 'डार्क मोड',
      'dark_mode_subtitle': 'डार्क थीम अभी सक्रिय है',
      'theme_title': 'थीम',
      'theme_subtitle': 'अपनी पसंदीदा लुक चुनें',
      'map_provider_section': 'मैप प्रोवाइडर',
      'language_region_section': 'भाषा और क्षेत्र',
      'privacy_security_section': 'गोपनीयता और सुरक्षा',
      'about_section': 'ऐप के बारे में',
      'language_picker_title': 'भाषा / Mozhi',
      'language_picker_subtitle': 'ऐप टेक्स्ट कैसा दिखे यह चुनें',
    },
    // FIX (Nizam's i18n request): added Malayalam as the 5th supported
    // language, keyed off the SAME keys as en/ta/tg/hi so every existing
    // t('key') call site automatically gains Malayalam support with zero
    // other code changes.
    'ml': {
      'app_title': 'my allin1',
      'greeting': 'നമസ്കാരം',
      'what_need_today': 'ഇന്ന് നിങ്ങൾക്ക് എന്ത് വേണം?',
      'bike_taxi_title': 'ബൈക്ക് ടാക്സി',
      'bike_taxi_subtitle': 'ஈரோட്ടിൽ വേഗതയേറിയ യാത്ര',
      'food_delivery_title': 'ഫുഡ് ഡെലിവറി',
      'food_delivery_subtitle': '16-ാം റോഡ് സ്പെഷ്യൽസ്',
      'grocery_title': 'പലചരക്ക്',
      'grocery_subtitle': 'പുതിയതും വേഗതയേറിയതും',
      'tech_store_title': 'ടെക് സ്റ്റോർ',
      'tech_store_subtitle': 'NJ TECH ഗാഡ്ജെറ്റുകൾ',
      'custom_order_title': 'കസ്റ്റം ഓർഡർ',
      'custom_order_subtitle': 'പ്രത്യേക സേവനത്തിന് ചോദിക്കൂ',
      'broadband_title': 'ബ്രോഡ്ബാൻഡ് / വൈഫൈ',
      'broadband_subtitle': 'നിങ്ങളുടെ ഇന്റർനെറ്റ് സേവനം മാനേജ് ചെയ്യുക',
      'mobile_puncture_title': 'മൊബൈൽ പഞ്ചർ',
      'mobile_puncture_subtitle': 'വേഗത്തിലുള്ള പഞ്ചർ റിപ്പയർ',
      'pharmacy_title': 'ഫാർമസി',
      'pharmacy_subtitle': 'മരുന്നുകൾ ഡെലിവർ ചെയ്യും',
      'book_puncture': 'പഞ്ചറിന് ബുക്ക് ചെയ്യണോ?',
      'call_now': 'ഇപ്പോൾ വിളിക്കൂ',
      'later': 'പിന്നീട്',
      'service_coming_soon': 'ഉടൻ വരുന്നു!',
      'language_label': 'ഭാഷ',
      'home_label': 'ഹോം',
      'chat_label': 'ലൈവ് റേറ്റ്സ്',
      'rides_label': 'പ്ലേ സോൺ',
      'account_label': 'അക്കൗണ്ട്',
      'my_rides_label': 'എന്റെ യാത്രകൾ',
      'live_rates_label': 'ലൈവ് റേറ്റ്സ്',
      'play_zone_label': 'പ്ലേ സോൺ',
      'live_label': 'ലൈവ്',
      'erode_label': 'ஈரோடு, தமிழ்நாடு',
      'live_rates_title': 'ലൈവ് റേറ്റ്സ്',
      'live_rates_subtitle':
          'ஈரோட്ടിലെ സ്വർണ്ണം, വെള്ളി, ഇന്ധന വിലകൾ ഒറ്റനോട്ടത്തിൽ.',
      'today_price_label': 'ഇന്നത്തെ വില',
      'play_zone_title': 'പ്ലേ സോൺ',
      'play_zone_subtitle':
          'NJ TECH 3x3 പസിൽ പരിഹരിച്ച് നിങ്ങളുടെ മികച്ച സമയം തകർക്കൂ.',
      'sliding_puzzle_title': 'സ്ലൈഡിംഗ് പസിൽ ഗെയിം',
      'moves_label': 'നീക്കങ്ങൾ',
      'time_label': 'സമയം',
      'reset_label': 'റീസെറ്റ്',
      'play_again_label': 'വീണ്ടും കളിക്കൂ',
      'puzzle_instruction':
          'NJ TECH, ஈரோடு പാറ്റേൺ പീസുകൾ കൃത്യമായി അലൈൻ ചെയ്യൂ.',
      'solved_title': 'നിങ്ങൾ പരിഹരിച്ചു!',
      'solved_message_intro': 'മികച്ച നീക്കങ്ങൾ!',
      'bike_label': 'ബൈക്ക്',
      'auto_label': 'ഓട്ടോ',
      'cab_label': 'കാബ്',
      'parcel_label': 'പാഴ്സൽ',
      'mini_truck_label': 'മിനി ട്രക്ക്',
      'lorry_label': 'ലോറി',
      'emergency_manpower_label': 'എസ്ഒഎസ്',
      'where_to_go_hint': 'നിങ്ങൾ എവിടേക്കാണ് പോകേണ്ടത്?',
      'choose_vehicle_label': 'വാഹനം തിരഞ്ഞെടുക്കൂ',
      'distance_label': 'ദൂരം',
      'eta_label': 'ETA',
      'choose_destination_title': 'ലക്ഷ്യസ്ഥാനം തിരഞ്ഞെടുക്കൂ',
      'update_pickup_title': 'പിക്കപ്പ് അപ്ഡേറ്റ് ചെയ്യൂ',
      'drag_map_hint':
          'ஈரோட്ടിൽ സ്ഥലം കണ്ടെത്താൻ മാപ്പ് വലിക്കുക അല്ലെങ്കിൽ 3 അക്ഷരങ്ങൾ ടൈപ്പ് ചെയ്യുക.',
      'pickup_location_label': 'പിക്കപ്പ് സ്ഥലം',
      'drop_destination_label': 'ഡ്രോപ്പ് ലക്ഷ്യസ്ഥാനം',
      'drop_pin_destination_title': 'ലക്ഷ്യസ്ഥാനത്തിന് പിൻ ഇടൂ',
      'drop_pin_pickup_title': 'പിക്കപ്പിന് പിൻ ഇടൂ',
      'finding_street_label': 'കൃത്യമായ തെരുവ് വിലാസം കണ്ടെത്തുന്നു...',
      'move_map_to_select_label': 'തിരഞ്ഞെടുക്കാൻ മാപ്പ് നീക്കൂ',
      'use_as_destination_label': 'ലക്ഷ്യസ്ഥാനമായി ഉപയോഗിക്കൂ',
      'use_as_pickup_label': 'പിക്കപ്പായി ഉപയോഗിക്കൂ',
      'pay_via_soundbox': 'Paytm സൗണ്ട്ബോക്സ് വഴി ബിൽ അടയ്ക്കൂ',
      'scan_soundbox_qr': 'സൗണ്ട്ബോക്സ് QR സ്കാൻ ചെയ്ത് പണം അടച്ചതിന് ശേഷം സ്ഥിരീകരിക്കൂ.',
      'awaiting_hero_payment': 'ഹീറോയുടെ സ്ഥിരീകരണത്തിനായി കാത്തിരിക്കുന്നു...',
      'scan_and_wait_hero': 'Paytm സൗണ്ട്ബോക്സ് സ്കാൻ ചെയ്ത് ഹീറോ നിങ്ങളുടെ ബിൽ സ്ഥിരീകരിക്കുന്നത് വരെ കാത്തിരിക്കൂ.',
      'open_upi_scan_soundbox': 'UPI ചൂസർ വഴി Paytm തുറന്ന്, ഹീറോയുടെ Paytm സൗണ്ട്ബോക്സ് സ്കാൻ ചെയ്ത്, കൃത്യമായ ബിൽ തുക പൂർത്തിയാക്കൂ.',
      'hero_booking_mega_title': 'ഹീറോ ബുക്കിംഗ്',
      'hero_booking_mega_subtitle': 'ഏത് ജോലിക്കും ഡെലിവറിക്കും ഒരു ഹീറോയെ ബുക്ക് ചെയ്യൂ',
      'taxi_mega_title': 'ടാക്സി & ട്രാൻസ്പോർട്ടേഷൻ',
      'taxi_mega_subtitle': 'ബൈക്ക്, ഓട്ടോ, കാബ്, പാഴ്സൽ & വാടക',
      'food_mega_subtitle': 'ஈரோட്ടിലെ ഏത് കടയിൽ നിന്നും ഓർഡർ ചെയ്യൂ!',
      'grocery_mega_title': 'പലചരക്ക് ഓർഡർ',
      'grocery_mega_subtitle': 'നിങ്ങളുടെ ലിസ്റ്റ് ടൈപ്പ് ചെയ്യൂ അല്ലെങ്കിൽ ഫോട്ടോ എടുക്കൂ',
      'electronics_mega_title': 'ഇലക്ട്രോണിക് സേവനങ്ങൾ',
      'electronics_mega_subtitle': 'മൊബൈൽ, ലാപ്ടോപ്, പിസി, സിസിടിവി, ടിവി & എസി',
      'carservice_mega_title': 'കാർ സർവീസ് & വാഷ്',
      'carservice_mega_subtitle': 'വാട്ടർ വാഷ്, റിപ്പയർ & പഴയ സ്പെയറുകൾ',
      'construction_mega_title': 'നിർമ്മാണം & ബിൽഡിംഗ്',
      'construction_mega_subtitle': 'ഉഷ കൺസ്ട്രക്ഷൻസ്, കരാറുകൾ & പ്ലാനുകൾ',
      'printing_mega_title': 'ഡിസൈനിംഗ് & പ്രിന്റിംഗ്',
      'printing_mega_subtitle': 'വിസിറ്റിംഗ് കാർഡ്, ഫ്ലെക്സ്, ബിൽ ബുക്ക് & നോട്ടീസ്',
      'otherservices_mega_title': 'മറ്റ് സേവനങ്ങൾ',
      'otherservices_mega_subtitle': 'ബ്രോഡ്ബാൻഡ്, മൊബൈൽ പഞ്ചർ & കൂടുതൽ',
      'other_internet_label': 'ഇന്റർനെറ്റ്',
      'other_puncture_label': 'പഞ്ചർ',
      'other_cleaning_label': 'ക്ലീനിംഗ്',
      'other_electrician_label': 'ഇലക്ട്രീഷ്യൻ',
      'greeting_hi': 'ഹായ്',
      'food_hub_prompt': 'നിങ്ങൾക്ക് എന്താണ് ഓർഡർ ചെയ്യേണ്ടത്?',
      'food_hub_custom_subtitle': 'ஈரோட்டിലെ ഏത് കടയിൽ നിന്നും ഓർഡർ ചെയ്യൂ',
      'food_hub_shops_heading': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട കടകളിൽ നിന്ന് ഓർഡർ ചെയ്യൂ',
      'food_hub_shops_subheading': 'അവരുടെ സൈറ്റിൽ ഓർഡർ ചെയ്ത് പണം അടയ്ക്കൂ — ഞങ്ങളുടെ ഹീറോ അത് എടുത്ത് നിങ്ങൾക്ക് എത്തിക്കും.',
      'settings_title': 'സെറ്റിംഗ്സ്',
      'notifications_section': 'അറിയിപ്പുകൾ',
      'push_notifications_title': 'പുഷ് അറിയിപ്പുകൾ',
      'push_notifications_subtitle': 'പുഷ് അറിയിപ്പുകൾ സ്വീകരിക്കൂ',
      'ride_alerts_title': 'റൈഡ് അലേർട്ടുകൾ',
      'ride_alerts_subtitle': 'നിങ്ങളുടെ യാത്രകളെക്കുറിച്ചുള്ള അപ്ഡേറ്റുകൾ നേടൂ',
      'promotional_alerts_title': 'പ്രമോഷണൽ അലേർട്ടുകൾ',
      'promotional_alerts_subtitle': 'ഓഫറുകളും ഡീലുകളും',
      'preferences_section': 'മുൻഗണനകൾ',
      'location_services_title': 'ലൊക്കേഷൻ സേവനങ്ങൾ',
      'location_services_subtitle': 'ആപ്പിന് ലൊക്കേഷൻ ആക്സസ് ചെയ്യാൻ അനുവദിക്കൂ',
      'biometric_login_title': 'ബയോമെട്രിക് ലോഗിൻ',
      'biometric_login_subtitle': 'വേഗത്തിലുള്ള ലോഗിനായി ഫിംഗർപ്രിന്റ് ഉപയോഗിക്കൂ',
      'dark_mode_title': 'ഡാർക്ക് മോഡ്',
      'dark_mode_subtitle': 'ഡാർക്ക് തീം നിലവിൽ സജീവമാണ്',
      'theme_title': 'തീം',
      'theme_subtitle': 'നിങ്ങളുടെ പ്രിയപ്പെട്ട ലുക്ക് തിരഞ്ഞെടുക്കൂ',
      'map_provider_section': 'മാപ്പ് പ്രൊവൈഡർ',
      'language_region_section': 'ഭാഷയും പ്രദേശവും',
      'privacy_security_section': 'സ്വകാര്യതയും സുരക്ഷയും',
      'about_section': 'ആപ്പിനെക്കുറിച്ച്',
      'language_picker_title': 'ഭാഷ / Mozhi',
      'language_picker_subtitle': 'ആപ്പ് ടെക്സ്റ്റ് എങ്ങനെ കാണണമെന്ന് തിരഞ്ഞെടുക്കൂ',
    },
  };

  String _languageCode;

  String get languageCode => _languageCode;

  String get languageLabel {
    switch (_languageCode) {
      case 'ta':
        return 'தமிழ்';
      case 'tg':
        return 'Tanglish';
      case 'hi':
        return 'हिन्दी';
      case 'ml':
        return 'മലയാളം';
      default:
        return 'English';
    }
  }

  String t(String key) {
    return _translations[_languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  Future<void> setLanguage(String code) async {
    if (!_translations.containsKey(code) || code == _languageCode) {
      return;
    }

    _languageCode = code;
    notifyListeners();

    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_prefsKey, _languageCode);
  }

  Future<void> _loadSavedLanguage() async {
    final prefs = await SharedPreferences.getInstance();
    final savedLanguage = prefs.getString(_prefsKey);
    if (savedLanguage == null ||
        !_translations.containsKey(savedLanguage) ||
        savedLanguage == _languageCode) {
      return;
    }

    _languageCode = savedLanguage;
    notifyListeners();
  }
}
