// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        return web;
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDipnXQFpwR1Zm4L3-XebKVgc1oPJhReME',
    appId: '1:357526153693:web:3a220b09b185f2ef4aee34',
    messagingSenderId: '357526153693',
    projectId: 'erode-super-app',
    authDomain: 'erode-super-app.firebaseapp.com',
    storageBucket: 'erode-super-app.firebasestorage.app',
    measurementId: 'G-S1SK2TW95E',
    databaseURL: 'https://erode-super-app-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDipnXQFpwR1Zm4L3-XebKVgc1oPJhReME',
    appId: '1:357526153693:android:4aee34',
    messagingSenderId: '357526153693',
    projectId: 'erode-super-app',
    authDomain: 'erode-super-app.firebaseapp.com',
    storageBucket: 'erode-super-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDipnXQFpwR1Zm4L3-XebKVgc1oPJhReME',
    appId: '1:357526153693:ios:4aee34',
    messagingSenderId: '357526153693',
    projectId: 'erode-super-app',
    authDomain: 'erode-super-app.firebaseapp.com',
    storageBucket: 'erode-super-app.firebasestorage.app',
  );
}
